import {
  BanknoteIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  FileChartColumnIcon,
  HistoryIcon,
  IdCardIcon,
  LandmarkIcon,
  ReceiptIcon,
  UserCogIcon,
  UsersIcon,
  WarehouseIcon,
} from "lucide-react"

import {
  makeSeries,
  panelItem,
  placeholderUrl as url,
  variantTitle,
  type DashboardVariant,
} from "./core"

export const erpVariants: DashboardVariant[] = [
  // ---------------------------- ERP · Superadministrador -------------------
  {
    system: "erp",
    role: "superadmin",
    title: variantTitle("erp", "superadmin"),
    navMain: [
      panelItem("erp", "superadmin"),
      { title: "Empleados", url, icon: UsersIcon },
      { title: "Nómina", url, icon: BanknoteIcon },
      { title: "Facturación CFDI", url, icon: ReceiptIcon },
      { title: "Contabilidad", url, icon: CalculatorIcon },
      { title: "Proveedores", url, icon: WarehouseIcon },
      { title: "Reportes financieros", url, icon: FileChartColumnIcon },
      { title: "Usuarios y permisos", url, icon: UserCogIcon },
      { title: "Configuración fiscal", url, icon: LandmarkIcon },
      { title: "Auditoría", url, icon: HistoryIcon },
    ],
    kpis: [
      {
        title: "Nómina mensual",
        value: "$850K",
        trend: "+2.1%",
        trendDirection: "up",
        footerTitle: "2 altas este mes",
        footerDescription: "86 empleados activos",
      },
      {
        title: "Facturado (mes)",
        value: "$2.4M",
        trend: "+18.2%",
        trendDirection: "up",
        footerTitle: "Mejor mes del año",
        footerDescription: "128 CFDI timbrados",
      },
      {
        title: "Cuentas por cobrar",
        value: "$420K",
        trend: "-6.4%",
        trendDirection: "down",
        footerTitle: "Cartera al corriente",
        footerDescription: "5 facturas vencen esta semana",
      },
      {
        title: "Gastos del mes",
        value: "$310K",
        trend: "+4.8%",
        trendDirection: "up",
        footerTitle: "Dentro del presupuesto",
        footerDescription: "Combustible: 62% del gasto",
      },
    ],
    chart: {
      title: "Ingresos vs gastos",
      description: "Miles de pesos por día · últimos 3 meses",
      seriesALabel: "Ingresos",
      seriesBLabel: "Gastos",
      data: makeSeries("erp-superadmin", 80, 45),
    },
    table: {
      title: "Facturas recientes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "cliente", label: "Cliente" },
        { key: "monto", label: "Monto" },
        { key: "estatus", label: "Estatus" },
        { key: "fecha", label: "Fecha" },
      ],
      rows: [
        { folio: "F-10234", cliente: "Transportes del Norte", monto: "$48,500", estatus: "Timbrada", fecha: "21 jul 2026" },
        { folio: "F-10233", cliente: "Aceros García", monto: "$112,300", estatus: "Timbrada", fecha: "20 jul 2026" },
        { folio: "F-10232", cliente: "Comercial Río", monto: "$23,900", estatus: "Por cobrar", fecha: "20 jul 2026" },
        { folio: "F-10231", cliente: "Minerales de Coahuila", monto: "$87,150", estatus: "Timbrada", fecha: "19 jul 2026" },
        { folio: "F-10230", cliente: "Grupo Industrial SAL", monto: "$156,800", estatus: "Cancelada", fecha: "18 jul 2026" },
        { folio: "F-10229", cliente: "Logística Frontera", monto: "$64,200", estatus: "Por cobrar", fecha: "18 jul 2026" },
      ],
    },
  },
  // ------------------------------- ERP · Administrador ---------------------
  {
    system: "erp",
    role: "admin",
    title: variantTitle("erp", "admin"),
    navMain: [
      panelItem("erp", "admin"),
      { title: "Empleados", url, icon: UsersIcon },
      { title: "Nómina", url, icon: BanknoteIcon },
      { title: "Facturación CFDI", url, icon: ReceiptIcon },
      { title: "Contabilidad", url, icon: CalculatorIcon },
      { title: "Proveedores", url, icon: WarehouseIcon },
      { title: "Reportes financieros", url, icon: FileChartColumnIcon },
    ],
    kpis: [
      {
        title: "Facturas por timbrar",
        value: "12",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "Carga de timbrado al alza",
        footerDescription: "Fecha límite: fin de mes",
      },
      {
        title: "Nómina quincenal",
        value: "$425K",
        trend: "+1.2%",
        trendDirection: "up",
        footerTitle: "Nómina al corriente",
        footerDescription: "Próxima dispersión: 31 jul",
      },
      {
        title: "Facturas vencidas",
        value: "5",
        trend: "-28.6%",
        trendDirection: "down",
        footerTitle: "Mejor cobranza este mes",
        footerDescription: "$96K por recuperar",
      },
      {
        title: "Gastos del mes",
        value: "$310K",
        trend: "+4.8%",
        trendDirection: "up",
        footerTitle: "Dentro del presupuesto",
        footerDescription: "Combustible: 62% del gasto",
      },
    ],
    chart: {
      title: "Facturación CFDI",
      description: "Timbradas vs pendientes · últimos 3 meses",
      seriesALabel: "Timbradas",
      seriesBLabel: "Pendientes",
      data: makeSeries("erp-admin", 9, 2),
    },
    table: {
      title: "Facturas CFDI",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "receptor", label: "Receptor" },
        { key: "total", label: "Total" },
        { key: "estatus", label: "Estatus" },
        { key: "pac", label: "PAC" },
      ],
      rows: [
        { folio: "F-10234", receptor: "Transportes del Norte SA", total: "$48,500", estatus: "Timbrada", pac: "Facturama" },
        { folio: "F-10233", receptor: "Aceros García SA de CV", total: "$112,300", estatus: "Timbrada", pac: "Facturama" },
        { folio: "F-10232", receptor: "Comercial Río SA", total: "$23,900", estatus: "Pendiente", pac: "Sin timbrar" },
        { folio: "F-10231", receptor: "Minerales de Coahuila", total: "$87,150", estatus: "Timbrada", pac: "Facturama" },
        { folio: "F-10230", receptor: "Grupo Industrial SAL", total: "$156,800", estatus: "Cancelada", pac: "Facturama" },
        { folio: "F-10229", receptor: "Logística Frontera", total: "$64,200", estatus: "Pendiente", pac: "Sin timbrar" },
      ],
    },
  },
  // --------------------------------- ERP · Usuario -------------------------
  {
    system: "erp",
    role: "user",
    title: variantTitle("erp", "user"),
    navMain: [
      panelItem("erp", "user"),
      { title: "Mis recibos", url, icon: ReceiptIcon },
      { title: "Solicitudes y vacaciones", url, icon: CalendarDaysIcon },
      { title: "Mis datos", url, icon: IdCardIcon },
    ],
    kpis: [
      {
        title: "Recibos disponibles",
        value: "24",
        trend: "+9.1%",
        trendDirection: "up",
        footerTitle: "2 recibos nuevos",
        footerDescription: "Última quincena incluida",
      },
      {
        title: "Vacaciones restantes",
        value: "8 días",
        trend: "-20%",
        trendDirection: "down",
        footerTitle: "2 días usados este mes",
        footerDescription: "Vencen en diciembre 2026",
      },
      {
        title: "Solicitudes pendientes",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Una solicitud en revisión",
        footerDescription: "Permiso del 15 jul aprobado",
      },
      {
        title: "Próximo pago",
        value: "31 jul",
        trend: "En 10 días",
        trendDirection: "up",
        footerTitle: "Dispersión programada",
        footerDescription: "Nómina quincenal ordinaria",
      },
    ],
    chart: {
      title: "Mis percepciones",
      description: "Miles de pesos por periodo · últimos 3 meses",
      seriesALabel: "Sueldo neto",
      seriesBLabel: "Bonos",
      data: makeSeries("erp-user", 14, 2),
    },
    table: {
      title: "Mis recibos de nómina",
      columns: [
        { key: "periodo", label: "Periodo" },
        { key: "fecha", label: "Fecha de pago" },
        { key: "neto", label: "Neto" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { periodo: "2026-Q14", fecha: "15 jul 2026", neto: "$14,250", estatus: "Pagado" },
        { periodo: "2026-Q13", fecha: "30 jun 2026", neto: "$14,250", estatus: "Pagado" },
        { periodo: "2026-Q12", fecha: "15 jun 2026", neto: "$13,900", estatus: "Pagado" },
        { periodo: "2026-Q11", fecha: "31 may 2026", neto: "$13,900", estatus: "Pagado" },
        { periodo: "2026-Q10", fecha: "15 may 2026", neto: "$14,600", estatus: "Pagado" },
        { periodo: "2026-Q09", fecha: "30 abr 2026", neto: "$13,900", estatus: "Pagado" },
      ],
    },
  },
]
