import {
  BellRingIcon,
  BoxesIcon,
  ClipboardListIcon,
  HistoryIcon,
  PackageIcon,
  PackageSearchIcon,
  ShoppingCartIcon,
  UserCogIcon,
  WarehouseIcon,
  WrenchIcon,
} from "lucide-react"

import {
  makeSeries,
  panelItem,
  placeholderUrl as url,
  variantTitle,
  type DashboardVariant,
} from "./core"

export const imsVariants: DashboardVariant[] = [
  // ---------------------------- IMS · Superadministrador -------------------
  {
    system: "ims",
    role: "superadmin",
    title: variantTitle("ims", "superadmin"),
    navMain: [
      panelItem("ims", "superadmin"),
      { title: "Inventario", url, icon: BoxesIcon },
      { title: "Refacciones", url, icon: PackageIcon },
      { title: "Mantenimiento", url, icon: WrenchIcon },
      { title: "Órdenes de compra", url, icon: ShoppingCartIcon },
      { title: "Proveedores", url, icon: WarehouseIcon },
      { title: "Alertas y umbrales", url, icon: BellRingIcon },
      { title: "Usuarios", url, icon: UserCogIcon },
      { title: "Auditoría", url, icon: HistoryIcon },
    ],
    kpis: [
      {
        title: "Valor de inventario",
        value: "$1.8M",
        trend: "+3.2%",
        trendDirection: "up",
        footerTitle: "Reposiciones del mes",
        footerDescription: "1,240 SKUs activos",
      },
      {
        title: "SKUs activos",
        value: "1,240",
        trend: "+1.5%",
        trendDirection: "up",
        footerTitle: "18 altas nuevas",
        footerDescription: "Catálogo actualizado",
      },
      {
        title: "Stock bajo",
        value: "23",
        trend: "+15%",
        trendDirection: "up",
        footerTitle: "Requiere reposición",
        footerDescription: "5 críticos: filtros y balatas",
      },
      {
        title: "Órdenes abiertas",
        value: "15",
        trend: "-11.8%",
        trendDirection: "down",
        footerTitle: "Buen flujo de compra",
        footerDescription: "3 llegan esta semana",
      },
    ],
    chart: {
      title: "Movimientos de inventario",
      description: "Entradas vs salidas · últimos 3 meses",
      seriesALabel: "Entradas",
      seriesBLabel: "Salidas",
      data: makeSeries("ims-superadmin", 34, 41),
    },
    table: {
      title: "Refacciones con stock bajo",
      columns: [
        { key: "sku", label: "SKU" },
        { key: "descripcion", label: "Descripción" },
        { key: "existencias", label: "Existencias" },
        { key: "minimo", label: "Mínimo" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { sku: "FLT-0012", descripcion: "Filtro de aceite motor", existencias: "4", minimo: "10", estatus: "Crítico" },
        { sku: "BLT-0034", descripcion: "Balatas delanteras", existencias: "6", minimo: "12", estatus: "Bajo" },
        { sku: "LLT-0221", descripcion: "Llanta 295/75R22.5", existencias: "8", minimo: "16", estatus: "Bajo" },
        { sku: "ACE-0005", descripcion: "Aceite 15W40 (cubo)", existencias: "9", minimo: "15", estatus: "Bajo" },
        { sku: "BAT-0041", descripcion: "Batería 12V 950CCA", existencias: "2", minimo: "6", estatus: "Crítico" },
        { sku: "MNG-0110", descripcion: "Manguera de radiador", existencias: "11", minimo: "14", estatus: "Bajo" },
      ],
    },
  },
  // ------------------------------- IMS · Administrador ---------------------
  {
    system: "ims",
    role: "admin",
    title: variantTitle("ims", "admin"),
    navMain: [
      panelItem("ims", "admin"),
      { title: "Inventario", url, icon: BoxesIcon },
      { title: "Refacciones", url, icon: PackageIcon },
      { title: "Mantenimiento", url, icon: WrenchIcon },
      { title: "Órdenes de compra", url, icon: ShoppingCartIcon },
      { title: "Proveedores", url, icon: WarehouseIcon },
      { title: "Alertas", url, icon: BellRingIcon },
    ],
    kpis: [
      {
        title: "Entradas del mes",
        value: "86",
        trend: "+7.5%",
        trendDirection: "up",
        footerTitle: "Recepciones al día",
        footerDescription: "12 recepciones esta semana",
      },
      {
        title: "Salidas del mes",
        value: "132",
        trend: "+10.6%",
        trendDirection: "up",
        footerTitle: "Alta rotación de refacciones",
        footerDescription: "Taller consume el 70%",
      },
      {
        title: "OC pendientes",
        value: "9",
        trend: "-18.2%",
        trendDirection: "down",
        footerTitle: "Compras más ágiles",
        footerDescription: "2 con proveedor externo",
      },
      {
        title: "Mantenimientos programados",
        value: "6",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "Programa preventivo activo",
        footerDescription: "2 preventivos, 4 correctivos",
      },
    ],
    chart: {
      title: "Entradas vs salidas",
      description: "Movimientos por día · últimos 3 meses",
      seriesALabel: "Entradas",
      seriesBLabel: "Salidas",
      data: makeSeries("ims-admin", 18, 24),
    },
    table: {
      title: "Órdenes de compra",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "proveedor", label: "Proveedor" },
        { key: "partidas", label: "Partidas" },
        { key: "total", label: "Total" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "OC-3051", proveedor: "Refacciones Diésel MX", partidas: "8", total: "$86,400", estatus: "En tránsito" },
        { folio: "OC-3050", proveedor: "Llantas del Sureste", partidas: "12", total: "$142,000", estatus: "Confirmada" },
        { folio: "OC-3049", proveedor: "AutoPartes Premier", partidas: "5", total: "$23,750", estatus: "Recibida" },
        { folio: "OC-3048", proveedor: "Frenos y Suspensiones SA", partidas: "6", total: "$58,900", estatus: "Parcial" },
        { folio: "OC-3047", proveedor: "Lubricantes del Norte", partidas: "3", total: "$17,300", estatus: "Recibida" },
        { folio: "OC-3046", proveedor: "Baterías EnergyPlus", partidas: "4", total: "$31,600", estatus: "Cancelada" },
      ],
    },
  },
  // --------------------------------- IMS · Usuario -------------------------
  {
    system: "ims",
    role: "user",
    title: variantTitle("ims", "user"),
    navMain: [
      panelItem("ims", "user"),
      { title: "Existencias", url, icon: PackageSearchIcon },
      { title: "Mis solicitudes", url, icon: ClipboardListIcon },
      { title: "Órdenes de trabajo", url, icon: WrenchIcon },
      { title: "Avisos", url, icon: BellRingIcon },
    ],
    kpis: [
      {
        title: "Mis solicitudes abiertas",
        value: "2",
        trend: "-33.3%",
        trendDirection: "down",
        footerTitle: "Una fue surtida ayer",
        footerDescription: "Promedio de surtido: 1.5 días",
      },
      {
        title: "OT asignadas",
        value: "3",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "Una orden nueva asignada",
        footerDescription: "Prioridad: unidad TR-009",
      },
      {
        title: "Consultas (semana)",
        value: "15",
        trend: "+25%",
        trendDirection: "up",
        footerTitle: "Uso frecuente del catálogo",
        footerDescription: "Lo más buscado: filtros",
      },
      {
        title: "Avisos sin leer",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Bandeja casi al día",
        footerDescription: "Cambio de almacén zona B",
      },
    ],
    chart: {
      title: "Mis movimientos",
      description: "Solicitado vs surtido · últimos 3 meses",
      seriesALabel: "Surtidas",
      seriesBLabel: "Solicitadas",
      data: makeSeries("ims-user", 6, 8),
    },
    table: {
      title: "Mis solicitudes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "refaccion", label: "Refacción" },
        { key: "cantidad", label: "Cantidad" },
        { key: "fecha", label: "Fecha" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "SOL-1042", refaccion: "Filtro de aceite motor", cantidad: "2", fecha: "21 jul 2026", estatus: "Pendiente" },
        { folio: "SOL-1041", refaccion: "Balatas delanteras", cantidad: "1 juego", fecha: "20 jul 2026", estatus: "Surtida" },
        { folio: "SOL-1039", refaccion: "Manguera de radiador", cantidad: "1", fecha: "19 jul 2026", estatus: "Surtida" },
        { folio: "SOL-1038", refaccion: "Aceite 15W40 (litro)", cantidad: "8", fecha: "18 jul 2026", estatus: "Rechazada" },
        { folio: "SOL-1036", refaccion: "Grasa multipropósito", cantidad: "2", fecha: "17 jul 2026", estatus: "Surtida" },
      ],
    },
  },
]
