import {
  FileChartColumnIcon,
  FileTextIcon,
  HistoryIcon,
  PackageIcon,
  RouteIcon,
  SatelliteIcon,
  Settings2Icon,
  SirenIcon,
  TruckIcon,
  UserCogIcon,
  UsersIcon,
} from "lucide-react"

import {
  makeSeries,
  panelItem,
  variantTitle,
  type DashboardVariant,
} from "./core"
import { moduleUrl } from "./module-types"

export const tmsVariants: DashboardVariant[] = [
  // ---------------------------- TMS · Superadministrador -------------------
  {
    system: "tms",
    role: "superadmin",
    title: variantTitle("tms", "superadmin"),
    navMain: [
      panelItem("tms", "superadmin"),
      { title: "Viajes", url: moduleUrl("tms", "superadmin", "viajes"), icon: RouteIcon },
      { title: "Flota y unidades", url: moduleUrl("tms", "superadmin", "flota"), icon: TruckIcon },
      { title: "Conductores", url: moduleUrl("tms", "superadmin", "conductores"), icon: UsersIcon },
      { title: "GPS y telemática", url: moduleUrl("tms", "superadmin", "gps-telematica"), icon: SatelliteIcon },
      { title: "Carta Porte", url: moduleUrl("tms", "superadmin", "carta-porte"), icon: FileTextIcon },
      { title: "Reportes", url: moduleUrl("tms", "superadmin", "reportes"), icon: FileChartColumnIcon },
      { title: "Usuarios y roles", url: moduleUrl("tms", "superadmin", "usuarios-roles"), icon: UserCogIcon },
      { title: "Auditoría", url: moduleUrl("tms", "superadmin", "auditoria"), icon: HistoryIcon },
      { title: "Configuración", url: moduleUrl("tms", "superadmin", "configuracion"), icon: Settings2Icon },
    ],
    kpis: [
      {
        title: "Viajes activos",
        value: "128",
        trend: "+12.5%",
        trendDirection: "up",
        footerTitle: "Incremento este mes",
        footerDescription: "Comparado con junio 2026",
      },
      {
        title: "Unidades en ruta",
        value: "42/50",
        trend: "+8.2%",
        trendDirection: "up",
        footerTitle: "Alta disponibilidad de flota",
        footerDescription: "84% de la flota operando",
      },
      {
        title: "Ingresos del mes",
        value: "$1.2M",
        trend: "+15.3%",
        trendDirection: "up",
        footerTitle: "Supera la meta mensual",
        footerDescription: "Proyección de cierre: $1.5M",
      },
      {
        title: "Cumplimiento de entregas",
        value: "96.4%",
        trend: "-1.2%",
        trendDirection: "down",
        footerTitle: "Ligera baja este periodo",
        footerDescription: "Meta: 98% de entregas a tiempo",
      },
    ],
    chart: {
      title: "Viajes por día",
      description: "Completados vs cancelados · últimos 3 meses",
      seriesALabel: "Completados",
      seriesBLabel: "Cancelados",
      data: makeSeries("tms-superadmin", 24, 5),
    },
    table: {
      title: "Flota de unidades",
      columns: [
        { key: "unidad", label: "Unidad" },
        { key: "tipo", label: "Tipo" },
        { key: "operador", label: "Operador" },
        { key: "estatus", label: "Estatus" },
        { key: "ubicacion", label: "Ubicación" },
        { key: "gps", label: "Última señal GPS" },
      ],
      rows: [
        { unidad: "TR-001", tipo: "Torton", operador: "Juan Pérez", estatus: "En ruta", ubicacion: "Monterrey, NL", gps: "Hace 2 min" },
        { unidad: "TR-004", tipo: "Rabón", operador: "Carlos Gómez", estatus: "En patio", ubicacion: "Patio Saltillo", gps: "Hace 5 min" },
        { unidad: "TR-007", tipo: "Sencillo", operador: "Ana Martínez", estatus: "En ruta", ubicacion: "San Luis Potosí, SLP", gps: "Hace 1 min" },
        { unidad: "TR-009", tipo: "Torton", operador: "Luis Hernández", estatus: "Mantenimiento", ubicacion: "Taller Monterrey", gps: "Hace 1 h" },
        { unidad: "TR-012", tipo: "Full", operador: "María López", estatus: "En ruta", ubicacion: "Reynosa, Tamps.", gps: "Hace 3 min" },
        { unidad: "TR-015", tipo: "Rabón", operador: "Jorge Ramírez", estatus: "Cargando", ubicacion: "Cedis Apodaca", gps: "Hace 8 min" },
      ],
    },
  },
  // ------------------------------- TMS · Administrador ---------------------
  {
    system: "tms",
    role: "admin",
    title: variantTitle("tms", "admin"),
    navMain: [
      panelItem("tms", "admin"),
      { title: "Viajes", url: moduleUrl("tms", "admin", "viajes"), icon: RouteIcon },
      { title: "Flota y unidades", url: moduleUrl("tms", "admin", "flota"), icon: TruckIcon },
      { title: "Conductores", url: moduleUrl("tms", "admin", "conductores"), icon: UsersIcon },
      { title: "GPS y telemática", url: moduleUrl("tms", "admin", "gps-telematica"), icon: SatelliteIcon },
      { title: "Carta Porte", url: moduleUrl("tms", "admin", "carta-porte"), icon: FileTextIcon },
      { title: "Incidencias", url: moduleUrl("tms", "admin", "incidencias"), icon: SirenIcon },
      { title: "Reportes", url: moduleUrl("tms", "admin", "reportes"), icon: FileChartColumnIcon },
    ],
    kpis: [
      {
        title: "Viajes programados hoy",
        value: "18",
        trend: "+16.7%",
        trendDirection: "up",
        footerTitle: "Más viajes que ayer",
        footerDescription: "Alta demanda en ruta norte",
      },
      {
        title: "En tránsito",
        value: "12",
        trend: "+9.1%",
        trendDirection: "up",
        footerTitle: "Operación estable",
        footerDescription: "Sin retrasos críticos reportados",
      },
      {
        title: "Entregas completadas",
        value: "34",
        trend: "+13.3%",
        trendDirection: "up",
        footerTitle: "Buen ritmo de entrega",
        footerDescription: "Semana con mayor cumplimiento",
      },
      {
        title: "Incidencias abiertas",
        value: "3",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "Menos incidencias que ayer",
        footerDescription: "2 mecánicas, 1 documental",
      },
    ],
    chart: {
      title: "Embarques por día",
      description: "Programados vs completados · últimos 3 meses",
      seriesALabel: "Programados",
      seriesBLabel: "Completados",
      data: makeSeries("tms-admin", 22, 19),
    },
    table: {
      title: "Viajes activos",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "origen", label: "Origen" },
        { key: "destino", label: "Destino" },
        { key: "operador", label: "Operador" },
        { key: "unidad", label: "Unidad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "VJ-2041", origen: "Monterrey, NL", destino: "Reynosa, Tamps.", operador: "Juan Pérez", unidad: "TR-001", estatus: "En tránsito" },
        { folio: "VJ-2042", origen: "Saltillo, Coah.", destino: "CDMX", operador: "Ana Martínez", unidad: "TR-007", estatus: "Cargando" },
        { folio: "VJ-2043", origen: "Apodaca, NL", destino: "San Luis Potosí, SLP", operador: "Carlos Gómez", unidad: "TR-004", estatus: "Programado" },
        { folio: "VJ-2044", origen: "Monterrey, NL", destino: "Laredo, Tamps.", operador: "María López", unidad: "TR-012", estatus: "En aduana" },
        { folio: "VJ-2045", origen: "Ramos Arizpe, Coah.", destino: "Guadalajara, Jal.", operador: "Jorge Ramírez", unidad: "TR-015", estatus: "En tránsito" },
        { folio: "VJ-2046", origen: "Monterrey, NL", destino: "Querétaro, Qro.", operador: "Luis Hernández", unidad: "TR-009", estatus: "Demorado" },
      ],
    },
  },
  // --------------------------------- TMS · Usuario -------------------------
  {
    system: "tms",
    role: "user",
    title: variantTitle("tms", "user"),
    navMain: [
      panelItem("tms", "user"),
      { title: "Mis viajes", url: moduleUrl("tms", "user", "mis-viajes"), icon: RouteIcon },
      { title: "Entregas", url: moduleUrl("tms", "user", "entregas"), icon: PackageIcon },
      { title: "Documentos", url: moduleUrl("tms", "user", "documentos"), icon: FileTextIcon },
      { title: "Incidencias", url: moduleUrl("tms", "user", "incidencias"), icon: SirenIcon },
    ],
    kpis: [
      {
        title: "Mis viajes asignados",
        value: "4",
        trend: "+33.3%",
        trendDirection: "up",
        footerTitle: "Un viaje nuevo asignado",
        footerDescription: "2 salidas programadas esta semana",
      },
      {
        title: "Entregas de hoy",
        value: "2",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Menos entregas que ayer",
        footerDescription: "Siguiente entrega: 14:30 h",
      },
      {
        title: "Km recorridos (semana)",
        value: "1,240",
        trend: "+8.4%",
        trendDirection: "up",
        footerTitle: "Más kilómetros que la semana pasada",
        footerDescription: "Promedio diario: 248 km",
      },
      {
        title: "Incidencias reportadas",
        value: "1",
        trend: "-66.7%",
        trendDirection: "down",
        footerTitle: "Solo una incidencia activa",
        footerDescription: "Revisión de llantas en taller",
      },
    ],
    chart: {
      title: "Mis viajes por día",
      description: "Completados vs pendientes · últimos 3 meses",
      seriesALabel: "Completados",
      seriesBLabel: "Pendientes",
      data: makeSeries("tms-user", 3, 1),
    },
    table: {
      title: "Mis viajes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "ruta", label: "Ruta" },
        { key: "fecha", label: "Fecha" },
        { key: "estatus", label: "Estatus" },
        { key: "documentos", label: "Documentos" },
      ],
      rows: [
        { folio: "VJ-2041", ruta: "Monterrey → Reynosa", fecha: "21 jul 2026", estatus: "En tránsito", documentos: "Carta Porte lista" },
        { folio: "VJ-2038", ruta: "Monterrey → Saltillo", fecha: "20 jul 2026", estatus: "Entregado", documentos: "Firmada" },
        { folio: "VJ-2035", ruta: "Apodaca → Monclova", fecha: "19 jul 2026", estatus: "Entregado", documentos: "Firmada" },
        { folio: "VJ-2050", ruta: "Monterrey → Laredo", fecha: "23 jul 2026", estatus: "Programado", documentos: "Pendiente" },
        { folio: "VJ-2052", ruta: "Saltillo → Torreón", fecha: "24 jul 2026", estatus: "Programado", documentos: "Pendiente" },
      ],
    },
  },
]
