import {
  BanknoteIcon,
  CalculatorIcon,
  CalendarDaysIcon,
  FileChartColumnIcon,
  HistoryIcon,
  IdCardIcon,
  LandmarkIcon,
  ReceiptIcon,
  UserCogIcon,
  UsersIcon,
  WarehouseIcon,
} from "lucide-react"

import { makeSeries } from "../core"
import type { ModuleView } from "../module-types"

export const erpModules: ModuleView[] = [
  // ------------------------------ ERP · Empleados ---------------------------
  {
    system: "erp",
    slug: "empleados",
    title: "Empleados",
    description: "Plantilla, puestos, departamentos y antigüedad.",
    icon: UsersIcon,
    template: "lista",
    kpis: [
      {
        title: "Empleados activos",
        value: "86",
        trend: "+2.4%",
        trendDirection: "up",
        footerTitle: "2 altas este mes",
        footerDescription: "72 operativos, 14 admin",
      },
      {
        title: "En nómina",
        value: "84",
        trend: "+1.2%",
        trendDirection: "up",
        footerTitle: "Nómina completa",
        footerDescription: "2 en proceso de alta",
      },
      {
        title: "Vacaciones programadas",
        value: "9",
        trend: "+12.5%",
        trendDirection: "up",
        footerTitle: "Picos en verano",
        footerDescription: "Cobertura asegurada",
      },
      {
        title: "Cumpleaños del mes",
        value: "6",
        trend: "Agosto",
        trendDirection: "up",
        footerTitle: "¡Felicidades al equipo!",
        footerDescription: "Celebración el viernes",
      },
    ],
    table: {
      title: "Empleados",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "puesto", label: "Puesto" },
        { key: "departamento", label: "Departamento" },
        { key: "antiguedad", label: "Antigüedad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Laura Torres", puesto: "Gerente de operaciones", departamento: "Dirección", antiguedad: "8 años", estatus: "Activo" },
        { nombre: "Juan Pérez", puesto: "Operador", departamento: "Transporte", antiguedad: "5 años", estatus: "Activo" },
        { nombre: "Elena Ruiz", puesto: "Contadora", departamento: "Finanzas", antiguedad: "3 años", estatus: "Activo" },
        { nombre: "Ricardo Mata", puesto: "Supervisor de flota", departamento: "Mantenimiento", antiguedad: "6 años", estatus: "Activo" },
        { nombre: "Sofía Ávila", puesto: "Asistente RH", departamento: "Recursos humanos", antiguedad: "1 año", estatus: "Vacaciones" },
        { nombre: "Pedro Salas", puesto: "Operador", departamento: "Transporte", antiguedad: "2 años", estatus: "Incapacidad" },
      ],
    },
  },
  // -------------------------------- ERP · Nómina ----------------------------
  {
    system: "erp",
    slug: "nomina",
    title: "Nómina",
    description: "Cálculo, dispersión y timbrado de CFDI de nómina.",
    icon: BanknoteIcon,
    template: "lista",
    kpis: [
      {
        title: "Nómina mensual",
        value: "$850K",
        trend: "+2.1%",
        trendDirection: "up",
        footerTitle: "2 altas este mes",
        footerDescription: "86 empleados activos",
      },
      {
        title: "Quincena en curso",
        value: "$425K",
        trend: "+1.2%",
        trendDirection: "up",
        footerTitle: "Próxima dispersión: 31 jul",
        footerDescription: "Aguinaldo: dic 2026",
      },
      {
        title: "Incidencias de asistencia",
        value: "8",
        trend: "-20%",
        trendDirection: "down",
        footerTitle: "Menos retardos",
        footerDescription: "Control biométrico",
      },
      {
        title: "IMSS/ISR",
        value: "$98K",
        trend: "+3%",
        trendDirection: "up",
        footerTitle: "Provisiones al día",
        footerDescription: "Timbrado CFDI nómina",
      },
    ],
    chart: {
      title: "Nómina por quincena",
      description: "Neto a dispersar vs impuestos · últimos 3 meses",
      seriesALabel: "Neto",
      seriesBLabel: "Impuestos",
      data: makeSeries("mod-erp-nomina", 425, 98),
    },
    table: {
      title: "Periodos de nómina",
      columns: [
        { key: "periodo", label: "Periodo" },
        { key: "empleados", label: "Empleados" },
        { key: "bruto", label: "Bruto" },
        { key: "neto", label: "Neto" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { periodo: "2026-Q14", empleados: "86", bruto: "$512,400", neto: "$425,100", estatus: "Pagado" },
        { periodo: "2026-Q13", empleados: "85", bruto: "$508,900", neto: "$421,300", estatus: "Pagado" },
        { periodo: "2026-Q12", empleados: "85", bruto: "$505,700", neto: "$418,800", estatus: "Pagado" },
        { periodo: "2026-Q11", empleados: "84", bruto: "$499,200", neto: "$414,900", estatus: "Pagado" },
        { periodo: "2026-Q10", empleados: "84", bruto: "$501,400", neto: "$416,500", estatus: "Pagado" },
      ],
    },
  },
  // ------------------------------ ERP · Facturación -------------------------
  {
    system: "erp",
    slug: "facturacion-cfdi",
    title: "Facturación CFDI",
    description: "Emisión, timbrado y cancelación de comprobantes 4.0.",
    icon: ReceiptIcon,
    template: "lista",
    kpis: [
      {
        title: "CFDI timbrados (mes)",
        value: "128",
        trend: "+18.2%",
        trendDirection: "up",
        footerTitle: "Mejor mes del año",
        footerDescription: "PAC: Facturama",
      },
      {
        title: "Por timbrar",
        value: "12",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "Fin de mes como límite",
        footerDescription: "Prioridad clientes grandes",
      },
      {
        title: "Cancelados",
        value: "4",
        trend: "-33%",
        trendDirection: "down",
        footerTitle: "3 por error, 1 por cliente",
        footerDescription: "Proceso controlado",
      },
      {
        title: "Promedio de timbrado",
        value: "2.3 min",
        trend: "+15%",
        trendDirection: "up",
        footerTitle: "Respuesta PAC rápida",
        footerDescription: "Meta: 5 min",
      },
    ],
    chart: {
      title: "CFDI por día",
      description: "Timbrados vs cancelados · últimos 3 meses",
      seriesALabel: "Timbrados",
      seriesBLabel: "Cancelados",
      data: makeSeries("mod-erp-cfdi", 6, 2),
    },
    table: {
      title: "Facturas CFDI",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "receptor", label: "Receptor" },
        { key: "total", label: "Total" },
        { key: "estatus", label: "Estatus" },
        { key: "pac", label: "PAC" },
      ],
      rows: [
        { folio: "F-10234", receptor: "Transportes del Norte SA", total: "$48,500", estatus: "Timbrada", pac: "Facturama" },
        { folio: "F-10233", receptor: "Aceros García SA de CV", total: "$112,300", estatus: "Timbrada", pac: "Facturama" },
        { folio: "F-10232", receptor: "Comercial Río SA", total: "$23,900", estatus: "Pendiente", pac: "Sin timbrar" },
        { folio: "F-10231", receptor: "Minerales de Coahuila", total: "$87,150", estatus: "Timbrada", pac: "Facturama" },
        { folio: "F-10230", receptor: "Grupo Industrial SAL", total: "$156,800", estatus: "Cancelada", pac: "Facturama" },
        { folio: "F-10229", receptor: "Logística Frontera", total: "$64,200", estatus: "Pendiente", pac: "Sin timbrar" },
      ],
    },
  },
  // ------------------------------ ERP · Contabilidad ------------------------
  {
    system: "erp",
    slug: "contabilidad",
    title: "Contabilidad",
    description: "Caja, cuentas por cobrar/pagar y conciliación CONTPAQi.",
    icon: CalculatorIcon,
    template: "lista",
    kpis: [
      {
        title: "Ingresos del mes",
        value: "$2.4M",
        trend: "+18.2%",
        trendDirection: "up",
        footerTitle: "Mejor mes del año",
        footerDescription: "CONTPAQi sincronizado",
      },
      {
        title: "Gastos",
        value: "$310K",
        trend: "+4.8%",
        trendDirection: "up",
        footerTitle: "Dentro del presupuesto",
        footerDescription: "Combustible: 62%",
      },
      {
        title: "Por cobrar",
        value: "$420K",
        trend: "-6.4%",
        trendDirection: "down",
        footerTitle: "Cartera al corriente",
        footerDescription: "5 facturas vencen pronto",
      },
      {
        title: "Por pagar",
        value: "$180K",
        trend: "+12%",
        trendDirection: "up",
        footerTitle: "Proveedores a 30 días",
        footerDescription: "Sin moras",
      },
    ],
    chart: {
      title: "Flujo de caja",
      description: "Entradas vs salidas · últimos 3 meses",
      seriesALabel: "Entradas",
      seriesBLabel: "Salidas",
      data: makeSeries("mod-erp-contab", 80, 55),
    },
    table: {
      title: "Movimientos recientes",
      columns: [
        { key: "fecha", label: "Fecha" },
        { key: "concepto", label: "Concepto" },
        { key: "tipo", label: "Tipo" },
        { key: "monto", label: "Monto" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { fecha: "21 jul 2026", concepto: "Pago F-10231", tipo: "Ingreso", monto: "$87,150", estatus: "Conciliado" },
        { fecha: "20 jul 2026", concepto: "Combustible flota", tipo: "Egreso", monto: "$48,300", estatus: "Conciliado" },
        { fecha: "20 jul 2026", concepto: "Pago F-10229", tipo: "Ingreso", monto: "$64,200", estatus: "Pendiente" },
        { fecha: "19 jul 2026", concepto: "Nómina Q14", tipo: "Egreso", monto: "$425,100", estatus: "Conciliado" },
        { fecha: "18 jul 2026", concepto: "Servicio taller", tipo: "Egreso", monto: "$12,400", estatus: "Pendiente" },
      ],
    },
  },
  // ------------------------------ ERP · Proveedores -------------------------
  {
    system: "erp",
    slug: "proveedores",
    title: "Proveedores",
    description: "Catálogo de proveedores, pedidos y evaluación.",
    icon: WarehouseIcon,
    template: "lista",
    kpis: [
      {
        title: "Proveedores activos",
        value: "32",
        trend: "+6.7%",
        trendDirection: "up",
        footerTitle: "2 nuevos este mes",
        footerDescription: "Mayoría nacionales",
      },
      {
        title: "Pedidos en curso",
        value: "9",
        trend: "-10%",
        trendDirection: "down",
        footerTitle: "Compras ágiles",
        footerDescription: "3 con entrega esta semana",
      },
      {
        title: "Pagos pendientes",
        value: "6",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "Facturas a 30 días",
        footerDescription: "$180K por programar",
      },
      {
        title: "Evaluación promedio",
        value: "4.4/5",
        trend: "+0.3",
        trendDirection: "up",
        footerTitle: "Satisfacción estable",
        footerDescription: "12 evaluados",
      },
    ],
    table: {
      title: "Proveedores",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "rfc", label: "RFC" },
        { key: "categoria", label: "Categoría" },
        { key: "telefono", label: "Teléfono" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Refacciones Diésel MX", rfc: "RDM880214K31", categoria: "Refacciones", telefono: "81 8321 4450", estatus: "Activo" },
        { nombre: "Llantas del Sureste", rfc: "LDS910522N78", categoria: "Llantas", telefono: "81 8345 2210", estatus: "Activo" },
        { nombre: "Lubricantes del Norte", rfc: "LDN850913V12", categoria: "Lubricantes", telefono: "81 8377 9810", estatus: "Activo" },
        { nombre: "AutoPartes Premier", rfc: "APM920318R45", categoria: "Refacciones", telefono: "81 8300 5560", estatus: "En evaluación" },
        { nombre: "Combustibles del Bajío", rfc: "CDB940725W66", categoria: "Combustible", telefono: "442 231 8890", estatus: "Suspendido" },
      ],
    },
  },
  // --------------------------- ERP · Reportes financieros -------------------
  {
    system: "erp",
    slug: "reportes-financieros",
    title: "Reportes financieros",
    description: "Estados de resultados, flujo y proyecciones.",
    icon: FileChartColumnIcon,
    template: "analitica",
    charts: [
      {
        title: "Ingresos vs gastos",
        description: "Evolución mensual · últimos 3 meses",
        seriesALabel: "Ingresos",
        seriesBLabel: "Gastos",
        data: makeSeries("mod-erp-rep1", 85, 55),
      },
      {
        title: "Utilidad acumulada",
        description: "Margen operativo por periodo · últimos 3 meses",
        seriesALabel: "Utilidad",
        seriesBLabel: "Proyección",
        data: makeSeries("mod-erp-rep2", 30, 34),
      },
    ],
  },
  // --------------------------- ERP · Usuarios y permisos --------------------
  {
    system: "erp",
    slug: "usuarios-permisos",
    title: "Usuarios y permisos",
    description: "Accesos por rol a módulos financieros y de RH.",
    icon: UserCogIcon,
    template: "lista",
    kpis: [
      {
        title: "Usuarios ERP",
        value: "18",
        trend: "+5.9%",
        trendDirection: "up",
        footerTitle: "1 alta este mes",
        footerDescription: "Roles: admin, contador, RH",
      },
      {
        title: "Permisos auditados",
        value: "46",
        trend: "+2.2%",
        trendDirection: "up",
        footerTitle: "Revisión trimestral",
        footerDescription: "Sin conflictos",
      },
      {
        title: "Accesos suspendidos",
        value: "2",
        trend: "-33%",
        trendDirection: "down",
        footerTitle: "2 desactivaciones",
        footerDescription: "Motivo: baja de empleado",
      },
      {
        title: "Sesiones activas",
        value: "7",
        trend: "+16.7%",
        trendDirection: "up",
        footerTitle: "Uso diario",
        footerDescription: "Pico: 09:00 h",
      },
    ],
    table: {
      title: "Usuarios y permisos",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "correo", label: "Correo" },
        { key: "rol", label: "Rol" },
        { key: "modulos", label: "Módulos" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Laura Torres", correo: "laura@transrendon.mx", rol: "Administrador", modulos: "Todos", estatus: "Activo" },
        { nombre: "Elena Ruiz", correo: "elena@transrendon.mx", rol: "Contador", modulos: "Contabilidad, CFDI", estatus: "Activo" },
        { nombre: "Sofía Ávila", correo: "sofia@transrendon.mx", rol: "Recursos humanos", modulos: "Nómina, Empleados", estatus: "Activo" },
        { nombre: "Ricardo Mata", correo: "ricardo@transrendon.mx", rol: "Consulta", modulos: "Reportes", estatus: "Activo" },
        { nombre: "Pedro Salas", correo: "pedro@transrendon.mx", rol: "Consulta", modulos: "Mis recibos", estatus: "Suspendido" },
      ],
    },
  },
  // --------------------------- ERP · Configuración fiscal -------------------
  {
    system: "erp",
    slug: "configuracion-fiscal",
    title: "Configuración fiscal",
    description: "Datos SAT, certificados y configuración del PAC.",
    icon: LandmarkIcon,
    template: "formulario",
    form: [
      {
        title: "Datos fiscales",
        description: "Razón social, régimen y domicilio fiscal.",
        fields: [
          { key: "razon", label: "Razón social", type: "text", placeholder: "TransRendon S.A. de C.V." },
          { key: "rfc", label: "RFC", type: "text", placeholder: "TRS9807213K4" },
          { key: "regimen", label: "Régimen fiscal", type: "select", options: ["601 · General de Ley", "612 · Personas Físicas", "621 · Incorporación"] },
          { key: "cp", label: "Código postal", type: "text", placeholder: "64000" },
        ],
      },
      {
        title: "Certificados SAT",
        description: "CSF y llave privada para el timbrado.",
        fields: [
          { key: "csf", label: "Certificado CSF", type: "password", placeholder: "••••••••••••" },
          { key: "llave", label: "Llave privada", type: "password", placeholder: "••••••••••••" },
          { key: "no_cert", label: "Número de certificado", type: "text", placeholder: "00001000000400000000" },
        ],
      },
      {
        title: "PAC",
        description: "Proveedor autorizado de certificación.",
        fields: [
          { key: "pac", label: "Proveedor", type: "select", options: ["Facturama"] },
          { key: "pac_user", label: "Usuario PAC", type: "text", placeholder: "transrendon" },
          { key: "pac_pass", label: "Contraseña PAC", type: "password", placeholder: "••••••••••••" },
        ],
      },
    ],
  },
  // ------------------------------ ERP · Auditoría ---------------------------
  {
    system: "erp",
    slug: "auditoria",
    title: "Auditoría",
    description: "Bitácora de eventos financieros y administrativos.",
    icon: HistoryIcon,
    template: "lista",
    kpis: [
      {
        title: "Eventos financieros",
        value: "860",
        trend: "+5.5%",
        trendDirection: "up",
        footerTitle: "Volumen normal",
        footerDescription: "Registro íntegro",
      },
      {
        title: "Ediciones de nómina",
        value: "14",
        trend: "-22%",
        trendDirection: "down",
        footerTitle: "Menos correcciones",
        footerDescription: "Proceso validado",
      },
      {
        title: "Accesos a CFDI",
        value: "32",
        trend: "+14%",
        trendDirection: "up",
        footerTitle: "Revisión de timbrado",
        footerDescription: "Sin anomalías",
      },
      {
        title: "Exportaciones",
        value: "6",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "Reportes para contador",
        footerDescription: "Sin fugas",
      },
    ],
    table: {
      title: "Registro de auditoría",
      columns: [
        { key: "fecha", label: "Fecha" },
        { key: "usuario", label: "Usuario" },
        { key: "accion", label: "Acción" },
        { key: "modulo", label: "Módulo" },
        { key: "ip", label: "IP" },
      ],
      rows: [
        { fecha: "21 jul 2026 10:04", usuario: "Elena Ruiz", accion: "Timbrado CFDI F-10234", modulo: "Facturación CFDI", ip: "189.201.10.67" },
        { fecha: "21 jul 2026 09:31", usuario: "Sofía Ávila", accion: "Aprobó vacaciones", modulo: "Empleados", ip: "189.201.10.88" },
        { fecha: "20 jul 2026 17:12", usuario: "Sistema", accion: "Dispersión nómina Q14", modulo: "Nómina", ip: "API bancaria" },
        { fecha: "20 jul 2026 14:22", usuario: "Laura Torres", accion: "Actualizó configuración fiscal", modulo: "Configuración fiscal", ip: "189.201.10.45" },
        { fecha: "20 jul 2026 09:05", usuario: "Elena Ruiz", accion: "Exportó estados financieros", modulo: "Contabilidad", ip: "189.201.10.67" },
      ],
    },
  },
  // ------------------------------ ERP · Mis recibos -------------------------
  {
    system: "erp",
    slug: "mis-recibos",
    title: "Mis recibos",
    description: "Recibos de nómina, percepciones y deducciones.",
    icon: ReceiptIcon,
    template: "lista",
    kpis: [
      {
        title: "Recibos disponibles",
        value: "24",
        trend: "+9.1%",
        trendDirection: "up",
        footerTitle: "2 nuevos",
        footerDescription: "Última quincena incluida",
      },
      {
        title: "Neto último periodo",
        value: "$14,250",
        trend: "+2.5%",
        trendDirection: "up",
        footerTitle: "Quincena 14",
        footerDescription: "Depósito: 15 jul",
      },
      {
        title: "Percepciones extras",
        value: "2",
        trend: "+100%",
        trendDirection: "up",
        footerTitle: "Bonos de puntualidad",
        footerDescription: "Sin retenciones",
      },
      {
        title: "Descargados",
        value: "8",
        trend: "+33%",
        trendDirection: "up",
        footerTitle: "Timbrados listos",
        footerDescription: "CFDI disponibles",
      },
    ],
    table: {
      title: "Mis recibos de nómina",
      columns: [
        { key: "periodo", label: "Periodo" },
        { key: "fecha", label: "Fecha de pago" },
        { key: "neto", label: "Neto" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { periodo: "2026-Q14", fecha: "15 jul 2026", neto: "$14,250", estatus: "Pagado" },
        { periodo: "2026-Q13", fecha: "30 jun 2026", neto: "$14,250", estatus: "Pagado" },
        { periodo: "2026-Q12", fecha: "15 jun 2026", neto: "$13,900", estatus: "Pagado" },
        { periodo: "2026-Q11", fecha: "31 may 2026", neto: "$13,900", estatus: "Pagado" },
        { periodo: "2026-Q10", fecha: "15 may 2026", neto: "$14,600", estatus: "Pagado" },
      ],
    },
  },
  // ------------------------- ERP · Solicitudes y vacaciones -----------------
  {
    system: "erp",
    slug: "solicitudes-vacaciones",
    title: "Solicitudes y vacaciones",
    description: "Permisos, vacaciones y días disponibles.",
    icon: CalendarDaysIcon,
    template: "lista",
    kpis: [
      {
        title: "Días disponibles",
        value: "8",
        trend: "-20%",
        trendDirection: "down",
        footerTitle: "2 usados este mes",
        footerDescription: "Vencen dic 2026",
      },
      {
        title: "Solicitudes pendientes",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "En revisión por RH",
        footerDescription: "Permiso del 15 jul aprobado",
      },
      {
        title: "Aprobadas (año)",
        value: "4",
        trend: "+33%",
        trendDirection: "up",
        footerTitle: "Tomas planeadas",
        footerDescription: "2 en verano",
      },
      {
        title: "Por definir",
        value: "2",
        trend: "0%",
        trendDirection: "up",
        footerTitle: "Planea tu descanso",
        footerDescription: "Política: 30 días de aviso",
      },
    ],
    table: {
      title: "Mis solicitudes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "tipo", label: "Tipo" },
        { key: "desde", label: "Desde" },
        { key: "hasta", label: "Hasta" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "SOL-4012", tipo: "Vacaciones", desde: "10 ago 2026", hasta: "14 ago 2026", estatus: "Pendiente" },
        { folio: "SOL-4008", tipo: "Permiso", desde: "15 jul 2026", hasta: "15 jul 2026", estatus: "Aprobado" },
        { folio: "SOL-3991", tipo: "Vacaciones", desde: "22 jun 2026", hasta: "26 jun 2026", estatus: "Aprobado" },
        { folio: "SOL-3982", tipo: "Permiso", desde: "30 may 2026", hasta: "30 may 2026", estatus: "Aprobado" },
        { folio: "SOL-3974", tipo: "Vacaciones", desde: "04 may 2026", hasta: "08 may 2026", estatus: "Tomado" },
      ],
    },
  },
  // -------------------------------- ERP · Mis datos -------------------------
  {
    system: "erp",
    slug: "mis-datos",
    title: "Mis datos",
    description: "Información personal, laboral y de contacto.",
    icon: IdCardIcon,
    template: "formulario",
    form: [
      {
        title: "Datos personales",
        description: "Información básica de contacto.",
        fields: [
          { key: "nombre", label: "Nombre completo", type: "text", placeholder: "Ana Martínez López" },
          { key: "correo", label: "Correo", type: "email", placeholder: "ana@transrendon.mx" },
          { key: "telefono", label: "Teléfono", type: "text", placeholder: "81 8000 5678" },
          { key: "nacimiento", label: "Fecha de nacimiento", type: "text", placeholder: "DD/MM/AAAA" },
        ],
      },
      {
        title: "Datos laborales",
        description: "Puesto, sede y fecha de ingreso.",
        fields: [
          { key: "puesto", label: "Puesto", type: "select", options: ["Operador", "Supervisor", "Administrativo", "Recursos humanos", "Contabilidad"] },
          { key: "sede", label: "Sede", type: "select", options: ["Monterrey", "Saltillo", "CDMX"] },
          { key: "ingreso", label: "Fecha de ingreso", type: "text", placeholder: "DD/MM/AAAA" },
          { key: "curp", label: "CURP", type: "text", placeholder: "MALA900101HNLRPN02" },
        ],
      },
      {
        title: "Preferencias",
        description: "Notificaciones y moneda preferida.",
        fields: [
          { key: "notificaciones", label: "Canal de notificaciones", type: "select", options: ["Correo", "SMS", "App"] },
          { key: "moneda", label: "Moneda preferida", type: "select", options: ["MXN", "USD"] },
        ],
      },
    ],
  },
]