import {
  BellRingIcon,
  BoxesIcon,
  ClipboardListIcon,
  HistoryIcon,
  PackageIcon,
  PackageSearchIcon,
  ShoppingCartIcon,
  UserCogIcon,
  WarehouseIcon,
  WrenchIcon,
} from "lucide-react"

import { makeSeries } from "../core"
import type { ModuleView } from "../module-types"

export const imsModules: ModuleView[] = [
  // ------------------------------- IMS · Inventario -------------------------
  {
    system: "ims",
    slug: "inventario",
    title: "Inventario",
    description: "Valor, SKUs, rotación y movimientos de almacén.",
    icon: BoxesIcon,
    template: "lista",
    kpis: [
      {
        title: "Valor de inventario",
        value: "$1.8M",
        trend: "+3.2%",
        trendDirection: "up",
        footerTitle: "Reposiciones del mes",
        footerDescription: "1,240 SKUs activos",
      },
      {
        title: "SKUs activos",
        value: "1,240",
        trend: "+1.5%",
        trendDirection: "up",
        footerTitle: "18 altas",
        footerDescription: "Catálogo actualizado",
      },
      {
        title: "Stock bajo",
        value: "23",
        trend: "+15%",
        trendDirection: "up",
        footerTitle: "Requiere reposición",
        footerDescription: "5 críticos",
      },
      {
        title: "Rotación",
        value: "4.2",
        trend: "+0.4",
        trendDirection: "up",
        footerTitle: "Mensual",
        footerDescription: "Meta: 4.0",
      },
    ],
    chart: {
      title: "Movimientos de inventario",
      description: "Entradas vs salidas · últimos 3 meses",
      seriesALabel: "Entradas",
      seriesBLabel: "Salidas",
      data: makeSeries("mod-ims-inv", 34, 41),
    },
    table: {
      title: "Resumen por categoría",
      columns: [
        { key: "categoria", label: "Categoría" },
        { key: "skus", label: "SKUs" },
        { key: "valor", label: "Valor" },
        { key: "rotacion", label: "Rotación" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { categoria: "Filtros", skus: "142", valor: "$212,000", rotacion: "5.1", estatus: "Bajo" },
        { categoria: "Llantas", skus: "86", valor: "$486,000", rotacion: "3.4", estatus: "Activo" },
        { categoria: "Lubricantes", skus: "54", valor: "$98,000", rotacion: "6.2", estatus: "Activo" },
        { categoria: "Frenos", skus: "118", valor: "$264,000", rotacion: "4.0", estatus: "Crítico" },
        { categoria: "Eléctrico", skus: "210", valor: "$340,000", rotacion: "3.8", estatus: "Activo" },
        { categoria: "Carrocería", skus: "96", valor: "$150,000", rotacion: "2.1", estatus: "Bajo" },
      ],
    },
  },
  // ------------------------------- IMS · Refacciones ------------------------
  {
    system: "ims",
    slug: "refacciones",
    title: "Refacciones",
    description: "Catálogo de piezas, existencias y mínimos.",
    icon: PackageIcon,
    template: "lista",
    kpis: [
      {
        title: "Refacciones activas",
        value: "1,240",
        trend: "+1.5%",
        trendDirection: "up",
        footerTitle: "18 altas",
        footerDescription: "Catálogo vigente",
      },
      {
        title: "Sin stock",
        value: "5",
        trend: "-28%",
        trendDirection: "down",
        footerTitle: "Filtros y balatas",
        footerDescription: "OC en proceso",
      },
      {
        title: "Por caducar",
        value: "3",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "Rotación baja",
        footerDescription: "Revisar almacén B",
      },
      {
        title: "Precio promedio",
        value: "$1,240",
        trend: "+2.1%",
        trendDirection: "up",
        footerTitle: "Mercado estable",
        footerDescription: "Proveedores alineados",
      },
    ],
    table: {
      title: "Refacciones con stock bajo",
      columns: [
        { key: "sku", label: "SKU" },
        { key: "descripcion", label: "Descripción" },
        { key: "existencias", label: "Existencias" },
        { key: "minimo", label: "Mínimo" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { sku: "FLT-0012", descripcion: "Filtro de aceite motor", existencias: "4", minimo: "10", estatus: "Crítico" },
        { sku: "BLT-0034", descripcion: "Balatas delanteras", existencias: "6", minimo: "12", estatus: "Bajo" },
        { sku: "LLT-0221", descripcion: "Llanta 295/75R22.5", existencias: "8", minimo: "16", estatus: "Bajo" },
        { sku: "ACE-0005", descripcion: "Aceite 15W40 (cubo)", existencias: "9", minimo: "15", estatus: "Bajo" },
        { sku: "BAT-0041", descripcion: "Batería 12V 950CCA", existencias: "2", minimo: "6", estatus: "Crítico" },
        { sku: "MNG-0110", descripcion: "Manguera de radiador", existencias: "11", minimo: "14", estatus: "Bajo" },
      ],
    },
  },
  // ------------------------------- IMS · Mantenimiento ----------------------
  {
    system: "ims",
    slug: "mantenimiento",
    title: "Mantenimiento",
    description: "Programa preventivo y correctivo de la flota.",
    icon: WrenchIcon,
    template: "lista",
    kpis: [
      {
        title: "Mantenimientos programados",
        value: "6",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "2 preventivos, 4 correctivos",
        footerDescription: "Programa activo",
      },
      {
        title: "En taller",
        value: "3",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "TR-009 en curso",
        footerDescription: "Entrega estimada: jueves",
      },
      {
        title: "Preventivos (mes)",
        value: "14",
        trend: "+16.7%",
        trendDirection: "up",
        footerTitle: "Cobertura 92%",
        footerDescription: "Meta: 95%",
      },
      {
        title: "Fallas fuera de programa",
        value: "2",
        trend: "-33%",
        trendDirection: "down",
        footerTitle: "Menos imprevistos",
        footerDescription: "Mejora de diagnóstico",
      },
    ],
    chart: {
      title: "Mantenimientos por semana",
      description: "Preventivos vs correctivos · últimos 3 meses",
      seriesALabel: "Preventivos",
      seriesBLabel: "Correctivos",
      data: makeSeries("mod-ims-mant", 4, 3),
    },
    table: {
      title: "Programa de mantenimiento",
      columns: [
        { key: "unidad", label: "Unidad" },
        { key: "tipo", label: "Tipo" },
        { key: "fecha", label: "Fecha" },
        { key: "taller", label: "Taller" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { unidad: "TR-009", tipo: "Correctivo", fecha: "21 jul 2026", taller: "Taller Monterrey", estatus: "En proceso" },
        { unidad: "TR-001", tipo: "Preventivo", fecha: "24 jul 2026", taller: "Taller Monterrey", estatus: "Programado" },
        { unidad: "TR-007", tipo: "Preventivo", fecha: "25 jul 2026", taller: "Taller Saltillo", estatus: "Programado" },
        { unidad: "TR-012", tipo: "Correctivo", fecha: "22 jul 2026", taller: "Taller Reynosa", estatus: "Programado" },
        { unidad: "TR-004", tipo: "Preventivo", fecha: "18 jul 2026", taller: "Taller Saltillo", estatus: "Completado" },
        { unidad: "TR-015", tipo: "Correctivo", fecha: "17 jul 2026", taller: "Taller Monterrey", estatus: "Completado" },
      ],
    },
  },
  // ------------------------------ IMS · Órdenes de compra -------------------
  {
    system: "ims",
    slug: "ordenes-compra",
    title: "Órdenes de compra",
    description: "Compras a proveedores, recepciones y costos.",
    icon: ShoppingCartIcon,
    template: "lista",
    kpis: [
      {
        title: "OC abiertas",
        value: "9",
        trend: "-18.2%",
        trendDirection: "down",
        footerTitle: "Compras ágiles",
        footerDescription: "3 llegan esta semana",
      },
      {
        title: "Monto en tránsito",
        value: "$86K",
        trend: "+12%",
        trendDirection: "up",
        footerTitle: "Refacciones y llantas",
        footerDescription: "OC-3051 prioritaria",
      },
      {
        title: "Recibidas (mes)",
        value: "34",
        trend: "+9.7%",
        trendDirection: "up",
        footerTitle: "Recepciones al día",
        footerDescription: "Sin discrepancias",
      },
      {
        title: "Proveedores en compra",
        value: "7",
        trend: "+16.7%",
        trendDirection: "up",
        footerTitle: "Base amplia",
        footerDescription: "2 nuevos cotizados",
      },
    ],
    chart: {
      title: "Órdenes por semana",
      description: "Emitidas vs recibidas · últimos 3 meses",
      seriesALabel: "Emitidas",
      seriesBLabel: "Recibidas",
      data: makeSeries("mod-ims-oc", 8, 7),
    },
    table: {
      title: "Órdenes de compra",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "proveedor", label: "Proveedor" },
        { key: "partidas", label: "Partidas" },
        { key: "total", label: "Total" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "OC-3051", proveedor: "Refacciones Diésel MX", partidas: "8", total: "$86,400", estatus: "En tránsito" },
        { folio: "OC-3050", proveedor: "Llantas del Sureste", partidas: "12", total: "$142,000", estatus: "Confirmada" },
        { folio: "OC-3049", proveedor: "AutoPartes Premier", partidas: "5", total: "$23,750", estatus: "Recibida" },
        { folio: "OC-3048", proveedor: "Frenos y Suspensiones SA", partidas: "6", total: "$58,900", estatus: "Parcial" },
        { folio: "OC-3047", proveedor: "Lubricantes del Norte", partidas: "3", total: "$17,300", estatus: "Recibida" },
        { folio: "OC-3046", proveedor: "Baterías EnergyPlus", partidas: "4", total: "$31,600", estatus: "Cancelada" },
      ],
    },
  },
  // -------------------------------- IMS · Proveedores -----------------------
  {
    system: "ims",
    slug: "proveedores",
    title: "Proveedores",
    description: "Proveedores de refacciones, tiempos y evaluación.",
    icon: WarehouseIcon,
    template: "lista",
    kpis: [
      {
        title: "Proveedores",
        value: "18",
        trend: "+5.9%",
        trendDirection: "up",
        footerTitle: "1 nuevo este mes",
        footerDescription: "Refacciones y lubricantes",
      },
      {
        title: "Cotizaciones abiertas",
        value: "6",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "3 respondidas",
        footerDescription: "Comparativa en curso",
      },
      {
        title: "Lead time promedio",
        value: "3.2 días",
        trend: "-12%",
        trendDirection: "down",
        footerTitle: "Entrega más rápida",
        footerDescription: "Meta: 4 días",
      },
      {
        title: "Calificación",
        value: "4.5/5",
        trend: "+0.2",
        trendDirection: "up",
        footerTitle: "12 evaluados",
        footerDescription: "Sin quejas activas",
      },
    ],
    table: {
      title: "Proveedores",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "rfc", label: "RFC" },
        { key: "especialidad", label: "Especialidad" },
        { key: "lead_time", label: "Lead time" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Refacciones Diésel MX", rfc: "RDM880214K31", especialidad: "Filtros y frenos", lead_time: "2 días", estatus: "Activo" },
        { nombre: "Llantas del Sureste", rfc: "LDS910522N78", especialidad: "Llantas", lead_time: "4 días", estatus: "Activo" },
        { nombre: "Lubricantes del Norte", rfc: "LDN850913V12", especialidad: "Aceites y grasas", lead_time: "2 días", estatus: "Activo" },
        { nombre: "Baterías EnergyPlus", rfc: "BEP930615M32", especialidad: "Eléctrico", lead_time: "5 días", estatus: "En evaluación" },
        { nombre: "Frenos y Suspensiones SA", rfc: "FSS920421J65", especialidad: "Frenos", lead_time: "6 días", estatus: "Activo" },
      ],
    },
  },
  // -------------------------------- IMS · Alertas ---------------------------
  {
    system: "ims",
    slug: "alertas",
    title: "Alertas y umbrales",
    description: "Alertas de stock, mínimos y umbrales configurados.",
    icon: BellRingIcon,
    template: "lista",
    kpis: [
      {
        title: "Alertas activas",
        value: "8",
        trend: "+14.3%",
        trendDirection: "up",
        footerTitle: "5 stock bajo, 3 mantenimiento",
        footerDescription: "Seguimiento diario",
      },
      {
        title: "Críticas",
        value: "2",
        trend: "-33%",
        trendDirection: "down",
        footerTitle: "Filtros y baterías",
        footerDescription: "OC en proceso",
      },
      {
        title: "Enviadas (semana)",
        value: "34",
        trend: "+21%",
        trendDirection: "up",
        footerTitle: "Notificación automática",
        footerDescription: "Correo y app",
      },
      {
        title: "Atendidas",
        value: "26",
        trend: "+30%",
        trendDirection: "up",
        footerTitle: "Respuesta oportuna",
        footerDescription: "76% de atención",
      },
    ],
    table: {
      title: "Alertas activas",
      columns: [
        { key: "id", label: "ID" },
        { key: "tipo", label: "Tipo" },
        { key: "descripcion", label: "Descripción" },
        { key: "prioridad", label: "Prioridad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { id: "ALT-901", tipo: "Stock", descripcion: "Filtro FLT-0012 por debajo del mínimo", prioridad: "Alta", estatus: "Pendiente" },
        { id: "ALT-900", tipo: "Stock", descripcion: "Batería BAT-0041 crítica", prioridad: "Alta", estatus: "Pendiente" },
        { id: "ALT-899", tipo: "Mantenimiento", descripcion: "Preventivo TR-001 próximo", prioridad: "Media", estatus: "Programado" },
        { id: "ALT-897", tipo: "Stock", descripcion: "Llanta LLT-0221 bajo mínimo", prioridad: "Media", estatus: "Pendiente" },
        { id: "ALT-895", tipo: "Mantenimiento", descripcion: "Correctivo TR-009 en curso", prioridad: "Alta", estatus: "En proceso" },
      ],
    },
  },
  // --------------------------------- IMS · Usuarios -------------------------
  {
    system: "ims",
    slug: "usuarios",
    title: "Usuarios",
    description: "Accesos a almacén, catálogo y movimientos.",
    icon: UserCogIcon,
    template: "lista",
    kpis: [
      {
        title: "Usuarios IMS",
        value: "15",
        trend: "+7.1%",
        trendDirection: "up",
        footerTitle: "1 alta",
        footerDescription: "Almacén y taller",
      },
      {
        title: "Permisos de almacén",
        value: "9",
        trend: "+12.5%",
        trendDirection: "up",
        footerTitle: "Surtido y recepción",
        footerDescription: "Sin accesos indebidos",
      },
      {
        title: "Auditoría de accesos",
        value: "5",
        trend: "+25%",
        trendDirection: "up",
        footerTitle: "Revisión reciente",
        footerDescription: "Resultado limpio",
      },
      {
        title: "Sesiones activas",
        value: "4",
        trend: "+33%",
        trendDirection: "up",
        footerTitle: "Turno de almacén",
        footerDescription: "Pico: 08:00 h",
      },
    ],
    table: {
      title: "Usuarios",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "correo", label: "Correo" },
        { key: "rol", label: "Rol" },
        { key: "modulos", label: "Módulos" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Ricardo Mata", correo: "ricardo@transrendon.mx", rol: "Administrador", modulos: "Todos", estatus: "Activo" },
        { nombre: "Jorge Ramírez", correo: "jorge@transrendon.mx", rol: "Almacenista", modulos: "Inventario, Existencias", estatus: "Activo" },
        { nombre: "María López", correo: "maria@transrendon.mx", rol: "Almacenista", modulos: "Inventario, Existencias", estatus: "Activo" },
        { nombre: "Luis Hernández", correo: "luis@transrendon.mx", rol: "Mecánico", modulos: "Solicitudes, OT", estatus: "Activo" },
        { nombre: "Pedro Salas", correo: "pedro@transrendon.mx", rol: "Consulta", modulos: "Existencias", estatus: "Suspendido" },
      ],
    },
  },
  // -------------------------------- IMS · Auditoría -------------------------
  {
    system: "ims",
    slug: "auditoria",
    title: "Auditoría",
    description: "Bitácora de movimientos, ajustes y accesos.",
    icon: HistoryIcon,
    template: "lista",
    kpis: [
      {
        title: "Eventos de inventario",
        value: "720",
        trend: "+4.3%",
        trendDirection: "up",
        footerTitle: "Movimientos registrados",
        footerDescription: "Traza completa",
      },
      {
        title: "Ajustes de stock",
        value: "6",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "2 por daño, 4 por conteo",
        footerDescription: "Conteos cíclicos",
      },
      {
        title: "Movimientos de salida",
        value: "132",
        trend: "+10.6%",
        trendDirection: "up",
        footerTitle: "Taller consume 70%",
        footerDescription: "Control de salida",
      },
      {
        title: "Exportaciones",
        value: "4",
        trend: "+100%",
        trendDirection: "up",
        footerTitle: "Inventario para contabilidad",
        footerDescription: "Sin anomalías",
      },
    ],
    table: {
      title: "Registro de auditoría",
      columns: [
        { key: "fecha", label: "Fecha" },
        { key: "usuario", label: "Usuario" },
        { key: "accion", label: "Acción" },
        { key: "modulo", label: "Módulo" },
        { key: "ip", label: "IP" },
      ],
      rows: [
        { fecha: "21 jul 2026 11:20", usuario: "Jorge Ramírez", accion: "Surtió solicitud SOL-1041", modulo: "Inventario", ip: "189.201.10.130" },
        { fecha: "21 jul 2026 09:15", usuario: "Ricardo Mata", accion: "Ajuste de stock FLT-0012", modulo: "Refacciones", ip: "189.201.10.112" },
        { fecha: "20 jul 2026 16:40", usuario: "María López", accion: "Recepcionó OC-3049", modulo: "Órdenes de compra", ip: "189.201.10.131" },
        { fecha: "20 jul 2026 13:05", usuario: "Luis Hernández", accion: "Creó OT para TR-009", modulo: "Mantenimiento", ip: "189.201.10.142" },
        { fecha: "20 jul 2026 08:55", usuario: "Sistema", accion: "Conteo cíclico zona A", modulo: "Inventario", ip: "Proceso automático" },
      ],
    },
  },
  // -------------------------------- IMS · Existencias -----------------------
  {
    system: "ims",
    slug: "existencias",
    title: "Existencias",
    description: "Consulta de disponibilidad y precios de refacciones.",
    icon: PackageSearchIcon,
    template: "lista",
    kpis: [
      {
        title: "Consultas (semana)",
        value: "15",
        trend: "+25%",
        trendDirection: "up",
        footerTitle: "Uso del catálogo",
        footerDescription: "Lo más buscado: filtros",
      },
      {
        title: "Refacciones disponibles",
        value: "6",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "Disponibles para OT",
        footerDescription: "3 críticas",
      },
      {
        title: "Sin existencias",
        value: "2",
        trend: "0%",
        trendDirection: "up",
        footerTitle: "Requiere OC",
        footerDescription: "Balatas y baterías",
      },
      {
        title: "Precio promedio",
        value: "$860",
        trend: "+1.5%",
        trendDirection: "up",
        footerTitle: "Mercado estable",
        footerDescription: "Presupuesto: $1,500/mes",
      },
    ],
    table: {
      title: "Existencias consultadas",
      columns: [
        { key: "sku", label: "SKU" },
        { key: "descripcion", label: "Descripción" },
        { key: "existencias", label: "Existencias" },
        { key: "precio", label: "Precio" },
        { key: "ubicacion", label: "Ubicación" },
      ],
      rows: [
        { sku: "FLT-0012", descripcion: "Filtro de aceite motor", existencias: "4", precio: "$320", ubicacion: "Zona A-12" },
        { sku: "BLT-0034", descripcion: "Balatas delanteras", existencias: "6", precio: "$1,150", ubicacion: "Zona B-03" },
        { sku: "ACE-0005", descripcion: "Aceite 15W40 (cubo)", existencias: "9", precio: "$780", ubicacion: "Zona A-04" },
        { sku: "GRS-0011", descripcion: "Grasa multipropósito", existencias: "18", precio: "$210", ubicacion: "Zona A-05" },
        { sku: "MNG-0110", descripcion: "Manguera de radiador", existencias: "11", precio: "$440", ubicacion: "Zona B-07" },
      ],
    },
  },
  // ------------------------------ IMS · Mis solicitudes ---------------------
  {
    system: "ims",
    slug: "mis-solicitudes",
    title: "Mis solicitudes",
    description: "Solicitudes de refacciones al almacén.",
    icon: ClipboardListIcon,
    template: "lista",
    kpis: [
      {
        title: "Solicitudes abiertas",
        value: "2",
        trend: "-33.3%",
        trendDirection: "down",
        footerTitle: "Una surtida ayer",
        footerDescription: "Promedio 1.5 días",
      },
      {
        title: "Surtidas (mes)",
        value: "12",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "Flujo normal",
        footerDescription: "Sin rechazos",
      },
      {
        title: "Rechazadas",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Por cantidad",
        footerDescription: "Revisar requerimiento",
      },
      {
        title: "Prioridad alta",
        value: "1",
        trend: "+100%",
        trendDirection: "up",
        footerTitle: "Solicitud de ayer",
        footerDescription: "Unidad TR-009",
      },
    ],
    table: {
      title: "Mis solicitudes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "refaccion", label: "Refacción" },
        { key: "cantidad", label: "Cantidad" },
        { key: "fecha", label: "Fecha" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "SOL-1042", refaccion: "Filtro de aceite motor", cantidad: "2", fecha: "21 jul 2026", estatus: "Pendiente" },
        { folio: "SOL-1041", refaccion: "Balatas delanteras", cantidad: "1 juego", fecha: "20 jul 2026", estatus: "Surtida" },
        { folio: "SOL-1039", refaccion: "Manguera de radiador", cantidad: "1", fecha: "19 jul 2026", estatus: "Surtida" },
        { folio: "SOL-1038", refaccion: "Aceite 15W40 (litro)", cantidad: "8", fecha: "18 jul 2026", estatus: "Rechazada" },
        { folio: "SOL-1036", refaccion: "Grasa multipropósito", cantidad: "2", fecha: "17 jul 2026", estatus: "Surtida" },
      ],
    },
  },
  // ------------------------------ IMS · Órdenes de trabajo ------------------
  {
    system: "ims",
    slug: "ordenes-trabajo",
    title: "Órdenes de trabajo",
    description: "OT de mantenimiento asignadas al taller.",
    icon: WrenchIcon,
    template: "lista",
    kpis: [
      {
        title: "OT asignadas",
        value: "3",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "Una nueva",
        footerDescription: "Prioridad TR-009",
      },
      {
        title: "En proceso",
        value: "1",
        trend: "0%",
        trendDirection: "up",
        footerTitle: "Taller trabajando",
        footerDescription: "Avance 40%",
      },
      {
        title: "Completadas (mes)",
        value: "16",
        trend: "+14.3%",
        trendDirection: "up",
        footerTitle: "Buen ritmo",
        footerDescription: "Promedio 2.1 días",
      },
      {
        title: "Con retraso",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Pieza en tránsito",
        footerDescription: "Nueva fecha: viernes",
      },
    ],
    table: {
      title: "Órdenes de trabajo",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "unidad", label: "Unidad" },
        { key: "descripcion", label: "Descripción" },
        { key: "prioridad", label: "Prioridad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "OT-1121", unidad: "TR-009", descripcion: "Cambio de balatas traseras", prioridad: "Alta", estatus: "En proceso" },
        { folio: "OT-1120", unidad: "TR-001", descripcion: "Servicio preventivo 30,000 km", prioridad: "Media", estatus: "Programado" },
        { folio: "OT-1118", unidad: "TR-012", descripcion: "Revisión de frenos en aduana", prioridad: "Alta", estatus: "Programado" },
        { folio: "OT-1115", unidad: "TR-004", descripcion: "Cambio de llanta ponchada", prioridad: "Media", estatus: "Completado" },
        { folio: "OT-1112", unidad: "TR-015", descripcion: "Afinación de motor", prioridad: "Baja", estatus: "Completado" },
      ],
    },
  },
  // --------------------------------- IMS · Avisos ---------------------------
  {
    system: "ims",
    slug: "avisos",
    title: "Avisos",
    description: "Notificaciones del almacén y el taller.",
    icon: BellRingIcon,
    template: "lista",
    kpis: [
      {
        title: "Avisos sin leer",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Bandeja casi al día",
        footerDescription: "Cambio de almacén zona B",
      },
      {
        title: "Nuevos (semana)",
        value: "7",
        trend: "+40%",
        trendDirection: "up",
        footerTitle: "Notificaciones automáticas",
        footerDescription: "Revisa pendientes",
      },
      {
        title: "Importantes",
        value: "2",
        trend: "+100%",
        trendDirection: "up",
        footerTitle: "Stock crítico y OT",
        footerDescription: "Acción requerida",
      },
      {
        title: "Archivados",
        value: "34",
        trend: "+13%",
        trendDirection: "up",
        footerTitle: "Historial completo",
        footerDescription: "Sin pendientes ocultos",
      },
    ],
    table: {
      title: "Avisos",
      columns: [
        { key: "id", label: "ID" },
        { key: "tipo", label: "Tipo" },
        { key: "asunto", label: "Asunto" },
        { key: "fecha", label: "Fecha" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { id: "AV-771", tipo: "Almacén", asunto: "Cambio de ubicación zona B", fecha: "21 jul 2026", estatus: "Sin leer" },
        { id: "AV-770", tipo: "Stock", asunto: "Filtro FLT-0012 en nivel crítico", fecha: "21 jul 2026", estatus: "Leído" },
        { id: "AV-769", tipo: "Taller", asunto: "OT-1121 requiere refacción", fecha: "20 jul 2026", estatus: "Leído" },
        { id: "AV-768", tipo: "Compras", asunto: "OC-3051 confirmada por proveedor", fecha: "20 jul 2026", estatus: "Leído" },
        { id: "AV-766", tipo: "Almacén", asunto: "Conteo cíclico zona A completado", fecha: "19 jul 2026", estatus: "Leído" },
      ],
    },
  },
]