import {
  FileChartColumnIcon,
  FileTextIcon,
  HistoryIcon,
  PackageIcon,
  RouteIcon,
  SatelliteIcon,
  Settings2Icon,
  SirenIcon,
  TruckIcon,
  UserCogIcon,
  UsersIcon,
} from "lucide-react"

import { makeSeries } from "../core"
import type { ModuleView } from "../module-types"

export const tmsModules: ModuleView[] = [
  // -------------------------------- TMS · Viajes ----------------------------
  {
    system: "tms",
    slug: "viajes",
    title: "Viajes",
    description: "Programación, seguimiento y cierre de viajes.",
    icon: RouteIcon,
    template: "lista",
    kpis: [
      {
        title: "Viajes activos",
        value: "128",
        trend: "+12.5%",
        trendDirection: "up",
        footerTitle: "Incremento este mes",
        footerDescription: "Comparado con junio 2026",
      },
      {
        title: "En tránsito",
        value: "42",
        trend: "+8.2%",
        trendDirection: "up",
        footerTitle: "Operación estable",
        footerDescription: "Sin retrasos críticos",
      },
      {
        title: "Entregas hoy",
        value: "34",
        trend: "+13.3%",
        trendDirection: "up",
        footerTitle: "Buen ritmo de entrega",
        footerDescription: "Semana con mayor cumplimiento",
      },
      {
        title: "Cumplimiento",
        value: "96.4%",
        trend: "-1.2%",
        trendDirection: "down",
        footerTitle: "Ligera baja este periodo",
        footerDescription: "Meta: 98% a tiempo",
      },
    ],
    chart: {
      title: "Viajes por día",
      description: "Programados vs completados · últimos 3 meses",
      seriesALabel: "Programados",
      seriesBLabel: "Completados",
      data: makeSeries("mod-tms-viajes", 24, 22),
    },
    table: {
      title: "Viajes activos",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "origen", label: "Origen" },
        { key: "destino", label: "Destino" },
        { key: "operador", label: "Operador" },
        { key: "unidad", label: "Unidad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "VJ-2041", origen: "Monterrey, NL", destino: "Reynosa, Tamps.", operador: "Juan Pérez", unidad: "TR-001", estatus: "En tránsito" },
        { folio: "VJ-2042", origen: "Saltillo, Coah.", destino: "CDMX", operador: "Ana Martínez", unidad: "TR-007", estatus: "Cargando" },
        { folio: "VJ-2043", origen: "Apodaca, NL", destino: "San Luis Potosí, SLP", operador: "Carlos Gómez", unidad: "TR-004", estatus: "Programado" },
        { folio: "VJ-2044", origen: "Monterrey, NL", destino: "Laredo, Tamps.", operador: "María López", unidad: "TR-012", estatus: "En aduana" },
        { folio: "VJ-2045", origen: "Ramos Arizpe, Coah.", destino: "Guadalajara, Jal.", operador: "Jorge Ramírez", unidad: "TR-015", estatus: "En tránsito" },
        { folio: "VJ-2046", origen: "Monterrey, NL", destino: "Querétaro, Qro.", operador: "Luis Hernández", unidad: "TR-009", estatus: "Demorado" },
      ],
    },
  },
  // ------------------------------ TMS · Flota -------------------------------
  {
    system: "tms",
    slug: "flota",
    title: "Flota y unidades",
    description: "Inventario de unidades, disponibilidad y estado operativo.",
    icon: TruckIcon,
    template: "lista",
    kpis: [
      {
        title: "Unidades totales",
        value: "50",
        trend: "+2.0%",
        trendDirection: "up",
        footerTitle: "1 alta este mes",
        footerDescription: "3 fuera de servicio",
      },
      {
        title: "En ruta",
        value: "42",
        trend: "+8.2%",
        trendDirection: "up",
        footerTitle: "Alta disponibilidad",
        footerDescription: "84% de la flota operando",
      },
      {
        title: "En mantenimiento",
        value: "3",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "2 preventivos, 1 correctivo",
        footerDescription: "Taller Monterrey",
      },
      {
        title: "Km del mes",
        value: "48,200",
        trend: "+6.1%",
        trendDirection: "up",
        footerTitle: "Flota activa",
        footerDescription: "Promedio 1,204 km/unidad",
      },
    ],
    table: {
      title: "Flota de unidades",
      columns: [
        { key: "unidad", label: "Unidad" },
        { key: "tipo", label: "Tipo" },
        { key: "placa", label: "Placa" },
        { key: "operador", label: "Operador" },
        { key: "estatus", label: "Estatus" },
        { key: "gps", label: "Última señal GPS" },
      ],
      rows: [
        { unidad: "TR-001", tipo: "Torton", placa: "14A-2831", operador: "Juan Pérez", estatus: "En ruta", gps: "Hace 2 min" },
        { unidad: "TR-004", tipo: "Rabón", placa: "14B-1156", operador: "Carlos Gómez", estatus: "En patio", gps: "Hace 5 min" },
        { unidad: "TR-007", tipo: "Sencillo", placa: "14C-7742", operador: "Ana Martínez", estatus: "En ruta", gps: "Hace 1 min" },
        { unidad: "TR-009", tipo: "Torton", placa: "14A-3390", operador: "Luis Hernández", estatus: "Mantenimiento", gps: "Hace 1 h" },
        { unidad: "TR-012", tipo: "Full", placa: "14D-5521", operador: "María López", estatus: "En ruta", gps: "Hace 3 min" },
        { unidad: "TR-015", tipo: "Rabón", placa: "14B-9084", operador: "Jorge Ramírez", estatus: "Cargando", gps: "Hace 8 min" },
      ],
    },
  },
  // ----------------------------- TMS · Conductores --------------------------
  {
    system: "tms",
    slug: "conductores",
    title: "Conductores",
    description: "Plantilla de operadores, licencias y asignaciones.",
    icon: UsersIcon,
    template: "lista",
    kpis: [
      {
        title: "Conductores activos",
        value: "42",
        trend: "+2.4%",
        trendDirection: "up",
        footerTitle: "1 nuevo ingreso",
        footerDescription: "2 en descanso obligatorio",
      },
      {
        title: "Con viaje asignado",
        value: "38",
        trend: "+5.6%",
        trendDirection: "up",
        footerTitle: "Alta asignación",
        footerDescription: "Licencias al corriente",
      },
      {
        title: "Licencias por vencer",
        value: "3",
        trend: "-40%",
        trendDirection: "down",
        footerTitle: "3 renuevan en agosto",
        footerDescription: "Control documental activo",
      },
      {
        title: "Incidencias",
        value: "2",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Sin infracciones graves",
        footerDescription: "Registro limpio este mes",
      },
    ],
    table: {
      title: "Conductores",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "licencia", label: "Licencia" },
        { key: "vencimiento", label: "Vencimiento" },
        { key: "unidad", label: "Unidad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Juan Pérez", licencia: "LP-8812", vencimiento: "12 mar 2027", unidad: "TR-001", estatus: "En ruta" },
        { nombre: "Ana Martínez", licencia: "LP-7734", vencimiento: "04 ago 2026", unidad: "TR-007", estatus: "En ruta" },
        { nombre: "Carlos Gómez", licencia: "LP-6641", vencimiento: "28 nov 2026", unidad: "TR-004", estatus: "En patio" },
        { nombre: "María López", licencia: "LP-5529", vencimiento: "17 sep 2026", unidad: "TR-012", estatus: "En ruta" },
        { nombre: "Jorge Ramírez", licencia: "LP-4492", vencimiento: "02 ago 2026", unidad: "TR-015", estatus: "Cargando" },
        { nombre: "Luis Hernández", licencia: "LP-3317", vencimiento: "25 oct 2026", unidad: "—", estatus: "Descanso" },
      ],
    },
  },
  // --------------------------- TMS · GPS y telemática -----------------------
  {
    system: "tms",
    slug: "gps-telematica",
    title: "GPS y telemática",
    description: "Posición en tiempo real, eventos y rendimiento por unidad.",
    icon: SatelliteIcon,
    template: "lista",
    kpis: [
      {
        title: "Unidades con señal",
        value: "50",
        trend: "100%",
        trendDirection: "up",
        footerTitle: "Cobertura completa",
        footerDescription: "Samsara · Geotab",
      },
      {
        title: "Alertas de velocidad",
        value: "12",
        trend: "-20%",
        trendDirection: "down",
        footerTitle: "Menos excesos de velocidad",
        footerDescription: "Zona monitoreada 24/7",
      },
      {
        title: "Eventos de geocerca",
        value: "34",
        trend: "+10%",
        trendDirection: "up",
        footerTitle: "Actividad en patios",
        footerDescription: "8 salidas no autorizadas",
      },
      {
        title: "Consumo promedio",
        value: "4.8 km/l",
        trend: "+3.1%",
        trendDirection: "up",
        footerTitle: "Mejora de rendimiento",
        footerDescription: "Meta: 4.5 km/l",
      },
    ],
    chart: {
      title: "Posiciones registradas",
      description: "En ruta vs en patio · últimos 3 meses",
      seriesALabel: "En ruta",
      seriesBLabel: "En patio",
      data: makeSeries("mod-tms-gps", 38, 12),
    },
    table: {
      title: "Unidades en tiempo real",
      columns: [
        { key: "unidad", label: "Unidad" },
        { key: "ubicacion", label: "Ubicación" },
        { key: "velocidad", label: "Velocidad" },
        { key: "estatus", label: "Estatus" },
        { key: "senal", label: "Última señal" },
      ],
      rows: [
        { unidad: "TR-001", ubicacion: "Autopista 54, km 32", velocidad: "82 km/h", estatus: "En ruta", senal: "Hace 1 min" },
        { unidad: "TR-004", ubicacion: "Patio Saltillo", velocidad: "0 km/h", estatus: "En patio", senal: "Hace 3 min" },
        { unidad: "TR-007", ubicacion: "Libramiento Nte., SLP", velocidad: "94 km/h", estatus: "En ruta", senal: "Hace 1 min" },
        { unidad: "TR-012", ubicacion: "Reynosa, Tamps.", velocidad: "0 km/h", estatus: "Detenida", senal: "Hace 2 min" },
        { unidad: "TR-015", ubicacion: "Cedis Apodaca", velocidad: "12 km/h", estatus: "Cargando", senal: "Hace 1 min" },
      ],
    },
  },
  // ----------------------------- TMS · Carta Porte --------------------------
  {
    system: "tms",
    slug: "carta-porte",
    title: "Carta Porte",
    description: "Complemento SAT Carta Porte 3.1: emisión y validación.",
    icon: FileTextIcon,
    template: "lista",
    kpis: [
      {
        title: "Documentos emitidos",
        value: "64",
        trend: "+8.5%",
        trendDirection: "up",
        footerTitle: "Cumplimiento SAT",
        footerDescription: "Complemento Carta Porte 3.1",
      },
      {
        title: "Por timbrar",
        value: "7",
        trend: "-22%",
        trendDirection: "down",
        footerTitle: "Carga pendiente",
        footerDescription: "Validación de destino",
      },
      {
        title: "Con incidencias",
        value: "3",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "3 requieren corrección",
        footerDescription: "Datos de mercancía",
      },
      {
        title: "Cumplimiento",
        value: "98.2%",
        trend: "+1.1%",
        trendDirection: "up",
        footerTitle: "Documental al corriente",
        footerDescription: "Meta: 100%",
      },
    ],
    table: {
      title: "Carta Porte recientes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "viaje", label: "Viaje" },
        { key: "mercancia", label: "Mercancía" },
        { key: "destino", label: "Destino" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "CP-10421", viaje: "VJ-2041", mercancia: "Acero rolado", destino: "Reynosa, Tamps.", estatus: "Timbrada" },
        { folio: "CP-10420", viaje: "VJ-2042", mercancia: "Bebidas", destino: "CDMX", estatus: "Pendiente" },
        { folio: "CP-10419", viaje: "VJ-2039", mercancia: "Refacciones", destino: "Querétaro, Qro.", estatus: "Timbrada" },
        { folio: "CP-10418", viaje: "VJ-2037", mercancia: "Granel mineral", destino: "Monclova, Coah.", estatus: "Timbrada" },
        { folio: "CP-10417", viaje: "VJ-2035", mercancia: "Embotellado", destino: "Guadalajara, Jal.", estatus: "Con incidencia" },
      ],
    },
  },
  // ----------------------------- TMS · Incidencias --------------------------
  {
    system: "tms",
    slug: "incidencias",
    title: "Incidencias",
    description: "Averías, retrasos y problemas documentales en operación.",
    icon: SirenIcon,
    template: "lista",
    kpis: [
      {
        title: "Incidencias abiertas",
        value: "3",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "2 mecánicas, 1 documental",
        footerDescription: "Menos que ayer",
      },
      {
        title: "Resueltas (mes)",
        value: "18",
        trend: "+20%",
        trendDirection: "up",
        footerTitle: "Buen tiempo de respuesta",
        footerDescription: "Promedio 4.2 h",
      },
      {
        title: "Críticas",
        value: "1",
        trend: "-66.7%",
        trendDirection: "down",
        footerTitle: "Taller en curso",
        footerDescription: "Unidad TR-009",
      },
      {
        title: "En revisión",
        value: "2",
        trend: "0%",
        trendDirection: "up",
        footerTitle: "Seguimiento activo",
        footerDescription: "Pendientes de evidencia",
      },
    ],
    table: {
      title: "Incidencias activas",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "tipo", label: "Tipo" },
        { key: "unidad", label: "Unidad" },
        { key: "descripcion", label: "Descripción" },
        { key: "prioridad", label: "Prioridad" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "INC-2201", tipo: "Mecánica", unidad: "TR-009", descripcion: "Falla en frenos traseros", prioridad: "Alta", estatus: "En revisión" },
        { folio: "INC-2200", tipo: "Documental", unidad: "TR-015", descripcion: "Carta Porte con datos incorrectos", prioridad: "Media", estatus: "Pendiente" },
        { folio: "INC-2198", tipo: "Mecánica", unidad: "TR-004", descripcion: "Llanta ponchada en patio", prioridad: "Media", estatus: "En revisión" },
        { folio: "INC-2196", tipo: "Operativa", unidad: "TR-012", descripcion: "Retraso en aduana Laredo", prioridad: "Alta", estatus: "Resuelta" },
        { folio: "INC-2194", tipo: "Documental", unidad: "—", descripcion: "Firma de cliente pendiente", prioridad: "Baja", estatus: "Resuelta" },
      ],
    },
  },
  // ------------------------------ TMS · Reportes ----------------------------
  {
    system: "tms",
    slug: "reportes",
    title: "Reportes",
    description: "Análisis de operación, productividad y costos.",
    icon: FileChartColumnIcon,
    template: "analitica",
    charts: [
      {
        title: "Viajes por mes",
        description: "Evolución mensual de operaciones · últimos 3 meses",
        seriesALabel: "Viajes",
        seriesBLabel: "Entregas",
        data: makeSeries("mod-tms-rep1", 90, 82),
      },
      {
        title: "Utilidad operativa",
        description: "Ingresos vs costos · últimos 3 meses",
        seriesALabel: "Ingresos",
        seriesBLabel: "Costos",
        data: makeSeries("mod-tms-rep2", 85, 60),
      },
    ],
  },
  // --------------------------- TMS · Usuarios y roles -----------------------
  {
    system: "tms",
    slug: "usuarios-roles",
    title: "Usuarios y roles",
    description: "Control de accesos al sistema TMS por rol y área.",
    icon: UserCogIcon,
    template: "lista",
    kpis: [
      {
        title: "Usuarios activos",
        value: "24",
        trend: "+4.3%",
        trendDirection: "up",
        footerTitle: "1 alta este mes",
        footerDescription: "4 roles definidos",
      },
      {
        title: "Invitaciones pendientes",
        value: "3",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "2 operaciones, 1 RH",
        footerDescription: "Vencen en 7 días",
      },
      {
        title: "Con acceso TMS",
        value: "18",
        trend: "+12.5%",
        trendDirection: "up",
        footerTitle: "Mayor cobertura",
        footerDescription: "Operadores y supervisores",
      },
      {
        title: "Sesiones activas",
        value: "9",
        trend: "+28.6%",
        trendDirection: "up",
        footerTitle: "Uso en tiempo real",
        footerDescription: "Pico: 10:00–12:00",
      },
    ],
    table: {
      title: "Usuarios y roles",
      columns: [
        { key: "nombre", label: "Nombre" },
        { key: "correo", label: "Correo" },
        { key: "rol", label: "Rol" },
        { key: "sistema", label: "Sistema" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { nombre: "Laura Torres", correo: "laura@transrendon.mx", rol: "Superadministrador", sistema: "TMS · ERP · IMS", estatus: "Activo" },
        { nombre: "Ricardo Mata", correo: "ricardo@transrendon.mx", rol: "Administrador", sistema: "TMS", estatus: "Activo" },
        { nombre: "Sofía Ávila", correo: "sofia@transrendon.mx", rol: "Operaciones", sistema: "TMS", estatus: "Invitado" },
        { nombre: "Pedro Salas", correo: "pedro@transrendon.mx", rol: "Operador", sistema: "TMS", estatus: "Activo" },
        { nombre: "Elena Ruiz", correo: "elena@transrendon.mx", rol: "Finanzas", sistema: "ERP", estatus: "Bloqueado" },
      ],
    },
  },
  // ------------------------------ TMS · Auditoría ---------------------------
  {
    system: "tms",
    slug: "auditoria",
    title: "Auditoría",
    description: "Bitácora de eventos, accesos y cambios de configuración.",
    icon: HistoryIcon,
    template: "lista",
    kpis: [
      {
        title: "Eventos registrados (mes)",
        value: "1,240",
        trend: "+8.2%",
        trendDirection: "up",
        footerTitle: "Actividad creciente",
        footerDescription: "Registro completo",
      },
      {
        title: "Accesos externos",
        value: "12",
        trend: "-14%",
        trendDirection: "down",
        footerTitle: "Sin intentos no autorizados",
        footerDescription: "IPs verificadas",
      },
      {
        title: "Cambios críticos",
        value: "4",
        trend: "-20%",
        trendDirection: "down",
        footerTitle: "3 configuraciones, 1 permiso",
        footerDescription: "Auditoría en orden",
      },
      {
        title: "Exportaciones",
        value: "8",
        trend: "+33%",
        trendDirection: "up",
        footerTitle: "Reportes generados",
        footerDescription: "Sin fugas detectadas",
      },
    ],
    table: {
      title: "Registro de auditoría",
      columns: [
        { key: "fecha", label: "Fecha" },
        { key: "usuario", label: "Usuario" },
        { key: "accion", label: "Acción" },
        { key: "modulo", label: "Módulo" },
        { key: "ip", label: "IP" },
      ],
      rows: [
        { fecha: "21 jul 2026 09:12", usuario: "Laura Torres", accion: "Actualizó configuración", modulo: "Configuración", ip: "189.201.10.45" },
        { fecha: "21 jul 2026 08:47", usuario: "Ricardo Mata", accion: "Asignó viaje VJ-2046", modulo: "Viajes", ip: "189.201.10.112" },
        { fecha: "20 jul 2026 18:03", usuario: "Sistema", accion: "Timbrado de Carta Porte", modulo: "Carta Porte", ip: "API Facturama" },
        { fecha: "20 jul 2026 15:26", usuario: "Laura Torres", accion: "Creó usuario", modulo: "Usuarios y roles", ip: "189.201.10.45" },
        { fecha: "20 jul 2026 11:58", usuario: "Ricardo Mata", accion: "Exportó reporte", modulo: "Reportes", ip: "189.201.10.112" },
      ],
    },
  },
  // ---------------------------- TMS · Configuración -------------------------
  {
    system: "tms",
    slug: "configuracion",
    title: "Configuración",
    description: "Parámetros de empresa, operación e integraciones.",
    icon: Settings2Icon,
    template: "formulario",
    form: [
      {
        title: "Empresa",
        description: "Datos fiscales y de contacto del operador.",
        fields: [
          { key: "nombre", label: "Nombre de la empresa", type: "text", placeholder: "TransRendon S.A. de C.V." },
          { key: "rfc", label: "RFC", type: "text", placeholder: "TRS9807213K4" },
          { key: "telefono", label: "Teléfono", type: "text", placeholder: "81 8000 1234" },
          { key: "correo", label: "Correo de contacto", type: "email", placeholder: "contacto@transrendon.mx" },
        ],
      },
      {
        title: "Operación",
        description: "Zonas, horarios y políticas de despacho.",
        fields: [
          { key: "zona", label: "Zona de operación", type: "select", options: ["Norte", "Bajío", "Centro", "Pacífico"] },
          { key: "horario", label: "Horario de despacho", type: "select", options: ["06:00 h", "08:00 h", "10:00 h"] },
          { key: "moneda", label: "Moneda base", type: "select", options: ["MXN", "USD"] },
          { key: "tolerancia", label: "Tolerancia de retraso (min)", type: "text", placeholder: "15" },
        ],
      },
      {
        title: "Integraciones",
        description: "Credenciales de servicios externos (preview).",
        fields: [
          { key: "samsara", label: "API Key Samsara", type: "password", placeholder: "••••••••••••" },
          { key: "geotab", label: "Usuario Geotab", type: "text", placeholder: "admin@transrendon.mx" },
          { key: "facturama", label: "Token Facturama", type: "password", placeholder: "••••••••••••" },
        ],
      },
    ],
  },
  // ------------------------------ TMS · Mis viajes --------------------------
  {
    system: "tms",
    slug: "mis-viajes",
    title: "Mis viajes",
    description: "Viajes asignados y ruta personal de operación.",
    icon: RouteIcon,
    template: "lista",
    kpis: [
      {
        title: "Asignados",
        value: "4",
        trend: "+33.3%",
        trendDirection: "up",
        footerTitle: "Un viaje nuevo",
        footerDescription: "2 salen esta semana",
      },
      {
        title: "En curso",
        value: "1",
        trend: "0%",
        trendDirection: "up",
        footerTitle: "VJ-2041 en tránsito",
        footerDescription: "Reynosa · ETA 18:30",
      },
      {
        title: "Completados (mes)",
        value: "18",
        trend: "+12.5%",
        trendDirection: "up",
        footerTitle: "Buen historial",
        footerDescription: "0 retrasos reportados",
      },
      {
        title: "Km del mes",
        value: "6,420",
        trend: "+5.8%",
        trendDirection: "up",
        footerTitle: "Rendimiento estable",
        footerDescription: "Promedio 428 km/día",
      },
    ],
    table: {
      title: "Mis viajes",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "ruta", label: "Ruta" },
        { key: "fecha", label: "Fecha" },
        { key: "estatus", label: "Estatus" },
        { key: "documentos", label: "Documentos" },
      ],
      rows: [
        { folio: "VJ-2041", ruta: "Monterrey → Reynosa", fecha: "21 jul 2026", estatus: "En tránsito", documentos: "Carta Porte lista" },
        { folio: "VJ-2038", ruta: "Monterrey → Saltillo", fecha: "20 jul 2026", estatus: "Entregado", documentos: "Firmada" },
        { folio: "VJ-2035", ruta: "Apodaca → Monclova", fecha: "19 jul 2026", estatus: "Entregado", documentos: "Firmada" },
        { folio: "VJ-2050", ruta: "Monterrey → Laredo", fecha: "23 jul 2026", estatus: "Programado", documentos: "Pendiente" },
        { folio: "VJ-2052", ruta: "Saltillo → Torreón", fecha: "24 jul 2026", estatus: "Programado", documentos: "Pendiente" },
      ],
    },
  },
  // ------------------------------ TMS · Entregas ----------------------------
  {
    system: "tms",
    slug: "entregas",
    title: "Entregas",
    description: "Citas de descarga, firmas y evidencias de entrega.",
    icon: PackageIcon,
    template: "lista",
    kpis: [
      {
        title: "Entregas hoy",
        value: "2",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Menos que ayer",
        footerDescription: "Siguiente: 14:30 h",
      },
      {
        title: "Pendientes",
        value: "1",
        trend: "0%",
        trendDirection: "up",
        footerTitle: "Consolidado en camino",
        footerDescription: "Destino: Reynosa",
      },
      {
        title: "Documentos por firmar",
        value: "3",
        trend: "+50%",
        trendDirection: "up",
        footerTitle: "Firmas por capturar",
        footerDescription: "3 entregas de la semana",
      },
      {
        title: "Clientes atendidos",
        value: "8",
        trend: "+14%",
        trendDirection: "up",
        footerTitle: "Cobertura amplia",
        footerDescription: "Satisfacción 4.6/5",
      },
    ],
    table: {
      title: "Entregas",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "cliente", label: "Cliente" },
        { key: "destino", label: "Destino" },
        { key: "fecha", label: "Fecha" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "ENT-3312", cliente: "Aceros García", destino: "Reynosa, Tamps.", fecha: "21 jul 2026", estatus: "Entregado" },
        { folio: "ENT-3311", cliente: "Comercial Río", destino: "Saltillo, Coah.", fecha: "21 jul 2026", estatus: "Programado" },
        { folio: "ENT-3310", cliente: "Logística Frontera", destino: "Laredo, Tamps.", fecha: "20 jul 2026", estatus: "Entregado" },
        { folio: "ENT-3308", cliente: "Minerales de Coahuila", destino: "Monclova, Coah.", fecha: "20 jul 2026", estatus: "Entregado" },
        { folio: "ENT-3306", cliente: "Grupo Industrial SAL", destino: "CDMX", fecha: "19 jul 2026", estatus: "Pendiente" },
      ],
    },
  },
  // ------------------------------ TMS · Documentos --------------------------
  {
    system: "tms",
    slug: "documentos",
    title: "Documentos",
    description: "Guías, Cartas Porte y evidencia digital de cada viaje.",
    icon: FileTextIcon,
    template: "lista",
    kpis: [
      {
        title: "Documentos activos",
        value: "24",
        trend: "+9.1%",
        trendDirection: "up",
        footerTitle: "2 nuevos",
        footerDescription: "Carta Porte y guías",
      },
      {
        title: "Por firmar",
        value: "3",
        trend: "-25%",
        trendDirection: "down",
        footerTitle: "Firmas electrónicas",
        footerDescription: "2 pendientes de cliente",
      },
      {
        title: "Vencidos",
        value: "1",
        trend: "-50%",
        trendDirection: "down",
        footerTitle: "Renovación programada",
        footerDescription: "Licencia TR-007",
      },
      {
        title: "Archivo digital",
        value: "96%",
        trend: "+2%",
        trendDirection: "up",
        footerTitle: "Digitalización completa",
        footerDescription: "Meta: 100%",
      },
    ],
    table: {
      title: "Documentos",
      columns: [
        { key: "folio", label: "Folio" },
        { key: "tipo", label: "Tipo" },
        { key: "viaje", label: "Viaje" },
        { key: "emision", label: "Emisión" },
        { key: "estatus", label: "Estatus" },
      ],
      rows: [
        { folio: "DOC-5511", tipo: "Carta Porte", viaje: "VJ-2041", emision: "21 jul 2026", estatus: "Listo" },
        { folio: "DOC-5510", tipo: "Guía de remisión", viaje: "VJ-2042", emision: "21 jul 2026", estatus: "Pendiente" },
        { folio: "DOC-5509", tipo: "Carta Porte", viaje: "VJ-2039", emision: "20 jul 2026", estatus: "Listo" },
        { folio: "DOC-5508", tipo: "Constancia de entrega", viaje: "VJ-2038", emision: "20 jul 2026", estatus: "Firmado" },
        { folio: "DOC-5507", tipo: "Seguro de carga", viaje: "VJ-2035", emision: "19 jul 2026", estatus: "Vigente" },
      ],
    },
  },
]